### ISSUE TITLE
Object Reference Error while invoking Pyro Command

### ISSUE THREAD

**Issue by venh** [wixtoolset/issues#5727] opened 2017-12-03 16:57 UTC
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?

> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)

* Describe the problem and the steps to reproduce it.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by venh** [comment] 2017-12-03 17:22
WiX Version - 3.11.0.1701
Even though I am using Visual Studio 2017 Enterprise with .Net framework 4.6.1, I am not using it for Patch creation, since there is no support for Pyro in Visual Studio.

Currently, I am referring the following links for implementing a patch.
[Building Patch](http://petermarcu.blogspot.in/2007/06/wix-building-patch-using-new-patch_29.html)

[WiX Patching](
http://wixtoolset.org/documentation/manual/v3/patching/wix_patching.html)

It looks like Patch works only if the file (Sample.txt in this case), is inside the Version (1.0 or 1.1) folder. What if it is nested inside another folder inside the version folder or if it is inside a different folder. Then it is throwing Object reference error during the Pyro command invocation. . I have also tried with different values for Patch Classification like Update, Service Pack, Hotfix and so on. But the behavior seems to be the same. There seems to be very less documentation on this.  The details of the error are given below.

pyro.exe : error PYRO0001 : Object reference not set to an instance of an object.

Exception Type: System.NullReferenceException

Stack Trace:
   at Microsoft.Tools.WindowsInstallerXml.MediaRow.get_LastSequence()
   at Microsoft.Tools.WindowsInstallerXml.Patch.AttachTransforms(ArrayList transforms)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Pyro.Run(String[] args) in C:\build\work\eca3d12b\wix3\src\tools\pyro\py
ro.cs:line 201

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Tools.WindowsInstallerXml.MediaRow.get_LastSequence()
   at Microsoft.Tools.WindowsInstallerXml.Patch.AttachTransforms(ArrayList transforms)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Pyro.Run(String[] args) in C:\build\work\eca3d12b\wix3\src\tools\pyro\py
ro.cs:line 250
   at Microsoft.Tools.WindowsInstallerXml.Tools.Pyro.Main(String[] args) in C:\build\work\eca3d12b\wix3\src\tools\pyro\p
yro.cs:line 92

This looks like a bug to me. Please check.

**Comment by barnson** [comment] 2017-12-03 19:05
Duplicate of https://github.com/wixtoolset/issues/issues/4629.

**Closed by barnson** 2017-12-03 19:05 UTC
Labels: duplicate
