### ISSUE TITLE
.NET 4.8 redistributable downloads have changed its hash and file size.

### ISSUE THREAD

**Issue by ngbrown** [wixtoolset/issues#6440] opened 2021-04-28 00:59 UTC
* Which version of WiX are you building with?

> 3.12.2

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2015

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> .NET Framework 4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Both Windows 7 SP1 and Windows 10 (unknown build)

* Describe the problem and the steps to reproduce it.

> Bootstrapping the .NET framework with `NetFx48Redist` no longer works. The download is attempted multiple times, and finally fails:

```
[0480:0950][2021-04-27T17:20:54]e314: Failed to cache payload: NetFx48Redist from working path: C:\Users\win7\AppData\Local\Temp\{37B0BDAE-62CD-406D-AA98-3DDF84901EDE}\NetFx48Redist, error: 0x80070490.
[0480:0950][2021-04-27T17:20:54]e349: Application requested retry of payload: NetFx48Redist, encountered error: 0x80070490. Retrying...
[0480:0950][2021-04-27T17:20:54]w343: Prompt for source of package: NetFx48Redist, payload: NetFx48Redist, path: C:\Users\win7\Desktop\redist\ndp48-x86-x64-allos-enu.exe
[0480:0950][2021-04-27T17:20:57]i338: Acquiring package: NetFx48Redist, payload: NetFx48Redist, download from: https://go.microsoft.com/fwlink/?LinkId=2088631
[0BE4:09F8][2021-04-27T17:23:31]e000: Error 0x80070490: Failed to find expected public key in certificate chain.
[0BE4:09F8][2021-04-27T17:23:31]e000: Error 0x80070490: Failed to verify expected payload against actual certificate chain.
[0BE4:09F8][2021-04-27T17:23:31]e000: Error 0x80070490: Failed to verify signature of payload: NetFx48Redist
[0BE4:09F8][2021-04-27T17:23:31]e310: Failed to verify payload: NetFx48Redist at path: C:\ProgramData\Package Cache\.unverified\NetFx48Redist, error: 0x80070490. Deleting file.
[0BE4:09F8][2021-04-27T17:23:31]e000: Error 0x80070490: Failed to cache payload: NetFx48Redist
[0480:0950][2021-04-27T17:23:31]e314: Failed to cache payload: NetFx48Redist from working path: C:\Users\win7\AppData\Local\Temp\{37B0BDAE-62CD-406D-AA98-3DDF84901EDE}\NetFx48Redist, error: 0x80070490.
[0480:0A04][2021-04-27T17:23:31]e000: Error 0x80070490: Failed while caching, aborting execution.
[0BE4:0BF0][2021-04-27T17:23:31]i372: Session end, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{38c3d820-b454-43c2-a726-62c3b8e43c4a}, resume: None, restart: None, disable resume: No
```

At some point between 2020-04-20 and 2020-04-27, the file size, version number, and obviously SHA-1 of the file downloaded from `https://go.microsoft.com/fwlink/?LinkId=2088631` has changed.

![Screenshot - 2021-04-27_17-41-55](https://user-images.githubusercontent.com/228987/116329300-e8010c00-a77f-11eb-9ae8-55754abdc01d.png)

https://github.com/wixtoolset/wix3/blob/2ed6d7906c87bb65b75cfa0020e38a1b1dffa49b/src/ext/NetFxExtension/wixlib/NetFx48.wxs#L16

https://github.com/wixtoolset/wix3/blob/2ed6d7906c87bb65b75cfa0020e38a1b1dffa49b/src/ext/NetFxExtension/wixlib/NetFx48.wxs#L89-L96

The new SHA-1 value is `584FFD3BBB7F73CD149E4486F6465C838D847450`, with a file size of `121319368` bytes, and version of 4.8.4115.0. The digital signature is now only sha256 and shows as OK.

The smaller `NetFx48Web` download from `https://go.microsoft.com/fwlink/?LinkId=2085155` has also changed to a SHA-1 of `3727DC47F12D9EA5EBA87145228DFF0CE8076E25` and `1443272` bytes

* Describe the behavior you expected and how it differed from the actual behavior.

I realize this is an interaction with Microsoft controlled web endpoint. I would expect that the downloaded file be stable from these redistribution download URLs. How can WiX better handle this? Since the download is signed, can the digital signature be checked instead?

I'm also not sure how to update the `<RemotePayload/>` block because the certificate key and thumbprint might have changed too and I don't know where those values come from.

**Comment by rseanhall** [comment] 2021-04-28 01:01
This is a duplicate of https://github.com/wixtoolset/issues/issues/6438. You can run `heat.exe payload ndp.exe -o net48.wxs` to get updated values.

**Closed by rseanhall** 2021-04-28 01:01 UTC
Labels: triage
