### ISSUE TITLE
Using merge module causes WiX project to be never up-to-date

### ISSUE THREAD

**Issue by crusader-mike** [wixtoolset/issues#6203] opened 2020-07-02 16:57 UTC
* WiX version: 3.14.0.1703
* Visual Studio: 2017 (15.9.20)
* WiX Toolset Visual Studio Extension: 1.0.0.4
* .NET: 4.6.2

* Describe the problem and the steps to reproduce it.
> pressing F7 after successful build always results in package rebuild (as if some inputs have changed)
> See details [here](https://stackoverflow.com/questions/57631076/wix-project-is-never-up-to-date)

**Comment by rseanhall** [comment] 2020-07-03 00:08
Duplicate of https://github.com/wixtoolset/issues/issues/4048

**Closed by rseanhall** 2020-07-03 00:08 UTC
