### ISSUE TITLE
The wix -binaries.zip and the wix installer use different folder structures

### ISSUE THREAD

**Issue by JohnLudlow** [wixtoolset/issues#5375] opened 2016-08-09 17:08 UTC
- Which version of WiX are you building with?

3.10.2
- Which version of Visual Studio are you building with (if any)?

VS 2013 Update 5
- Which version of .NET are you building with?

.NET 4.5.2
- If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 2012 R2
- Describe the problem and the steps to reproduce it.

We have WiX 3.10.2 installed on our development desktops. However, it was deemed by the Powers That Be(tm) that things like the WiX toolset should have an XCopy install on the build machine.

Today, I created a C++ custom action DLL project using the Visual Studio template, and it added this as the additional include directory: 
          `$(WIX)\sdk\VS2013\inc`

This builds just fine on my local box, which I used the WiX 3.10.2 installer on.  However, this folder does not exist in the 3.10.2 zip. Instead, the folder is here:
          `$(WIX)\sdk\inc`

This means that the build fails on our build machine.

There are a couple of workarounds for this:
1. Copy the `sdk\inc` folder to `sdk\VS2013\inc`
2. Add the `sdk\inc` folder to the include directories list

It would be better if the WiX zip and install were consistent, however.
- Describe the behavior you expected and how it differed from the actual behavior.

The two should have the same folder structure. If this constitutes a breaking change and would need to be fixed in v4.0, then maybe an interim step could be to have the project template include both `$(WIX)\sdk\inc` and `$(WIX)\sdk\VS2013\inc`?

**Comment by rseanhall** [comment] 2016-08-09 17:24
Technically a duplicate of https://github.com/wixtoolset/issues/issues/4474, but I think we already did everything we planned on doing in v3.x for that issue so I'll leave this open for your suggestion.

**Comment by JohnLudlow** [comment] 2016-08-09 21:13
Oops. I did have a quick search, but apparently my search-fu was out to lunch. Whatever you guys want to do with it is fine. 

I would suggest a very safe way to handle it in v3 would be to simply add both paths to the include list as mentioned above, and one path or the other would be picked up. In v4, the two packages can be made consistent and the losing path can be dropped from the templates.

**Comment by Adnn** [comment] 2019-07-09 11:59
The problem appears to be larger, affecting content out of the SDK folder (the title still applies perfectly, plus this is one of the first Google results, so adding here for others to find)

When deploying Wix 3.11.1 from the installer, the binaries are installed under `$WIX/bin/`. When extracting the from the binaries archive, the binaries end up at the root, directly in `$WIX/`.

Is there a technical reason for such differences?

Overall, it makes our life more complicated because we have two kind of environments:
* Dev machines, where wix is deployed via installer
* CI build boxes, where Wix is deployed "per build" using the binaries archive.

This currently forces us to take extra step on the build boxes to match the dev environments.

**Comment by barnson** [comment] 2020-04-01 23:17
WiX v4 uses NuGet packages so the binaries .zips won't be useful.

**Closed by barnson** 2020-04-01 23:17 UTC
Labels: bug, duplicate
