### ISSUE TITLE
SqlExtension Incompatible with TLS 1.2

### ISSUE THREAD

**Issue by ArthurWelch** [wixtoolset/issues#5543] opened 2017-03-23 11:14 UTC
##Bug

* Which version of WiX are you building with?

> 3.10.3.3007
* Which version of Visual Studio are you building with (if any)?

>Visual Studio Enterprise 2015 14.0.23107.0 D14REL

* Which version of .NET are you building with?

> 4.6.01055

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows Server 2008 R2

* Describe the problem and the steps to reproduce it.

> When attempting to install a WiX package on a system with Microsoft SQL Server Express 2014 SP2 that has TLS 1.2 enabled, the install fails at the first instance of SqlString with the following error:

MSI (s) (84:48) [09:18:40:656]: Executing op: ActionStart(Name=ExecuteSqlStrings,Description=Executing SQL Strings,)
Action 9:18:40: ExecuteSqlStrings. Executing SQL Strings
MSI (s) (84:48) [09:18:40:656]: Executing op: CustomActionSchedule(Action=ExecuteSqlStrings,ActionType=25601,Source=BinaryData,Target=**********,CustomActionData=**********)
MSI (s) (84:70) [09:18:40:656]: Invoking remote custom action. DLL: C:\Windows\Installer\MSIEF3B.tmp, Entrypoint: ExecuteSqlStrings
ExecuteSqlStrings:  Error 0x80004005: failed to connect to database: 'master'

It appears that Microsoft is not supporting OLEDB (as used by the WiX SqlExtension) with TLS 1.2.

With TLS 1.2 disabled, the installation had succeeded.

* Describe the behavior you expected and how it differed from the actual behavior.

> The SqlStrings should succeed and the installation should complete successfully.

**Comment by RBANSALMICROSOFT** [comment] 2017-05-25 09:38
Any Update on it?  When are we planning to fix it?

**Comment by barnson** [comment] 2017-05-25 12:56
The bug is open for someone to work on. If you're volunteering, see [WiX Toolset Development](http://wixtoolset.org/development/).

**Comment by chandrapatibandla** [comment] 2017-09-28 08:32
Hi Bob Arnson,

I want to work for this fix.

Thanks,
Chandra Patibandla.

**Comment by barnson** [comment] 2017-09-28 16:05
Please create a [WIP][wip] to describe how you want to make the change.

[wip]: http://wixtoolset.org/development/wips/

**Comment by 24mu13** [comment] 2017-11-15 10:25
We found same issue very important when installing against Windows 2016 Server, for instance.
This means to tweak the server and *restart* SQL Service in order to use our installer...

Did you start working on that fix Chandra ?
S.

**Comment by gowreswaran** [comment] 2018-02-08 14:15
Do we have a link to WIP created for this issue?

**Comment by robmen** [comment] 2018-02-08 18:53
No WIP has been created. No one seems to be working on this issue at this time.

**Comment by RBANSALMS** [comment] 2018-03-05 09:32
I want to work on it.
I did not get any option to create new WIP, so here is the overview of how I am planning to fix it.

**FIX Details:**
SQLOLEDB does not have TLS1.2 support, so need to use SQL native Client for it.


In the SqlConnectDatabase() API in file ..\wix3\src\libs\dutil\sqlutil.cpp 

CoCreateInstance is being called with CLSID_SQLOLEDB as the first argument.
		hr = ::CoCreateInstance(CLSID_SQLOLEDB, NULL, CLSCTX_INPROC_SERVER,
 IID_IDBInitialize, (LPVOID*)&pidbInitialize);

Fix would be to call it with SQLNCLI_CLSID and if that fails, then as a fallback call with CLSID_SQLOLEDB.

OLD CODE:

	//obtain access to the SQLOLEDB provider
	hr = ::CoCreateInstance(SQLNCLI_CLSID, NULL, CLSCTX_INPROC_SERVER,
		IID_IDBInitialize, (LPVOID*)&pidbInitialize);
	ExitOnFailure(hr, "failed to create IID_IDBInitialize object");

NEW CODE:

	//obtain access to the SQLOLEDB provider  
	hr = ::CoCreateInstance(SQLNCLI_CLSID, NULL, CLSCTX_INPROC_SERVER,
		IID_IDBInitialize, (LPVOID*)&pidbInitialize);	
	if (FAILED(hr))	
	{		
	          hr = ::CoCreateInstance(CLSID_SQLOLEDB, NULL, CLSCTX_INPROC_SERVER,
			           IID_IDBInitialize, (LPVOID*)&pidbInitialize);	
	}
	ExitOnFailure(hr, "failed to create IID_IDBInitialize object");


Other related changes:
1. SQLNCLI.h file has to be copied to ...\wix3\src\libs\dutil\inc folder
2. SQLNCLI.h has to be included in the ....\wix3\src\libs\dutil\dutil.vcxproj
3. SQLNCLI.h has to be included in the ....\wix3\src\ext\ca\serverca\scasched\precomp.h
4. SQLNCLI.h has to be included in the ....\wix3\src\libs\dutil\inc\sqlutil.h
5. #define _SQLNCLI_OLEDB_IGNORE_DEPRECATION_WARNING_ needs to be defined in file ..\wix3\src\libs\dutil\sqlutil.cpp

**Comment by barnson** [comment] 2018-03-05 14:01
http://wixtoolset.org/development/wips/0000-wix-improvement-proposal/ describes how to create a WIP.

**Comment by RBANSALMS** [comment] 2018-03-06 15:29
WiX Improvement Proposal mentions that    "..... Not every change to the WiX toolset must have a WIP. Bug fixes, for example, are often sufficiently defined in the issue tracker....."
The change i am proposing is very minimal (only a 2-3 lines of change), does it require to go via WIP process?

**Comment by barnson** [comment] 2018-03-07 01:08
You can start a thread on the wix-devs mailing list to start. Adding sqlncli.h needs to be discussed.

**Comment by RBANSALMS** [comment] 2018-03-12 04:02
Hi barnson, I posted the solution last week, did you get the chance to look in it?

**Comment by robmen** [comment] 2018-05-04 07:34
This is fixed in WiX v3.14.0.1703

**Comment by eqr** [comment] 2018-05-28 10:35
@robmen Where can I get WiX 3.14? The Releases page stops at 3.11.

**Comment by robmen** [comment] 2018-05-28 16:11
@eqr look in the "Weekly Releases".

**Comment by eqr** [comment] 2018-05-28 16:34
@robmen Thank you.

**Comment by ArthurWelch** [comment] 2018-05-29 10:32
When would it be available in a “Stable” build?

Thank You,
Art

**Comment by robmen** [comment] 2018-05-29 10:34
@ArthurWelch when WiX v4.0 is marked stable (sometime later this year).

**Comment by ArthurWelch** [comment] 2018-05-29 10:42
Thank You.

**Comment by buddyfavors** [comment] 2018-06-18 19:23
@robmen Is there a ballpark (summer/fall/winter) on the ETA? We would ideally like to wait for the weekly build to become a stable release.

A lot of our customers are credit unions and they need to be complaint for PCI Data Security Standard (PCI DSS) for safeguarding payment data they are required to update to newer TLS.

**Comment by nairswat** [comment] 2019-05-09 04:37
@robmen Any latest development on releasing a stable build for Wix 3.14 or Wix 4.0. We would really like to consume this fix as most of our installation environment is shifting to TLS 1.2

**Comment by lhfiedler** [comment] 2019-08-09 19:22
Hi, 
Where are the weekly releases of 3.14 for download? 
Would it be possible to get this fix pushed up to a stable v3 release since we use nuget?   
Windows machines by default require a secure version of tls now, and this is breaking us ...

**Comment by BMurri** [comment] 2019-08-09 19:30
WiX v3.14 is intended to be released with the rollout of WiX v4. Until then, the latest builds can be found by following the link from this [page](https://wixtoolset.org/releases/).

WiX v4 is intended to be obtained from NuGet. WiX v3 isn't (although 3rd parties have packaged builds and placed them on NuGet, even giving credit to @robmen).

**Comment by sbraswell** [comment] 2019-09-24 17:34
We have an environment where TLS 1.1 and 1.0 are both disabled on the SQL server. We are using the SqlDatabase and SqlString components to deploy database changes during install which are failing in this environment. If we enable TLS 1.0 and 1.1 then the installation succeeds.

@robmen mentions that this issue is fixed in 3.14.0.1703 and @barnson mentioned that this issue is a duplicate of https://github.com/wixtoolset/issues/issues/5794. So I'm not sure what to try next.

We have built the installer using WiX v3.14.0.1703 as well as v3.14.0.2812 with similar results.

Error:
MSI (s) (64:1C) [13:18:20:146]: Invoking remote custom action. DLL: C:\Windows\Installer\MSIFDF0.tmp, Entrypoint: CreateDatabase
CreateDatabase:  Error 0x80040154: failed to create to database: 'TmpDatabase', error: unknown error
Error 26201. Error -2147221164: failed to create SQL database: TmpDatabase, error detail: unknown error.
MSI (s) (64!DC) [13:18:39:273]: Product: TestProduct 15.2.0.11 -- Error 26201. Error -2147221164: failed to create SQL database: TmpDatabase, error detail: unknown error.

CustomAction CreateDatabase returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

**Comment by BMurri** [comment] 2019-09-24 18:20
I believe that v3.14.0.2927 would be the first build that would contain all parts of that fix. The newest v3.14 is v3.11.2.4516.

**Comment by sbraswell** [comment] 2019-09-24 19:58
@BMurri thanks for the response. Unfortunately, it wasn't because we weren't using the right build. It wasn't obvious here, but for this to work the target machine must have the SQL Native Client (2012) installed. The change made to WiX was to prioritize the connection using the SQL Native Client which supports TLS 1.2. If that connection attempt fails it falls back to SQL OLEDB which until recently doesn't support TLS 1.2.

For us, it was a perfect storm of mismatched dependencies and prerequisites that caused the issues. Now we have a working configuration. As long as the target system has the SQL Native Client (2012) installed then TLS 1.0 and 1.1 can be disabled. Hope this will help someone else out there running into the same issues.

Thanks!

**Comment by BMurri** [comment] 2019-09-24 22:46
I'm glad it's working and thank you for closing the loop with useful information for whomever runs across this next

**Comment by rseanhall** [comment] 2020-04-02 03:23
@firegiantco Need this one in v4, too.

**Closed** 2021-04-12 22:26 UTC
Labels: enhancement, extensions, port-from-wix3
