### ISSUE TITLE
Unable to install WiX v3 - Visual Studio 2022 Extension on Visual Studio 2022 v17.5.2

### ISSUE THREAD

**Issue by GeekSamurai** [wixtoolset/issues#7281] opened 2023-03-17 06:58 UTC
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
> 3.11.2.4516

* Which version of Visual Studio are you building with (if any)?
> Visual Studio 2022 v17.5.2

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
> WiX v3 - Visual Studio 2022 Extension 3.11.2.4516

* Which version of .NET are you building with?
> NA

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
> NA

* Describe the problem and the steps to reproduce it.
> We tried installing WiX v3 - Visual Studio 2022 Extension on Visual Studio 2022 v17.5.2 is failing. Attached is log file for more details.

* Describe the behavior you expected and how it differed from the actual behavior.
> NA
[dd_VSIXInstaller_20230317120745_7e68.log](https://github.com/wixtoolset/issues/files/10998562/dd_VSIXInstaller_20230317120745_7e68.log))

**Comment by robmen** [comment] 2023-03-17 07:06
Duplicate of #7266

```log
3/17/2023 12:07:46 - Signature Details...
3/17/2023 12:07:46 - 	Extension is signed with an invalid certificate
3/17/2023 12:07:46 - 		(UntrustedRoot)     : A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
3/17/2023 12:07:46 - 		(RevocationStatusUnknown): The revocation function was unable to check revocation for the certificate.
3/17/2023 12:07:46 - 		(OfflineRevocation) : The revocation function was unable to check revocation because the revocation server was offline.
```

**Closed by robmen** 2023-03-17 07:06 UTC
Labels: duplicate

**Comment by GeekSamurai** [comment] 2023-03-17 09:05
Please let me know what is the certificate name and where I can get the it?
