### ISSUE TITLE
VS2022 64-bit build fails

### ISSUE THREAD

**Issue by MikeAtETI** [wixtoolset/issues#6927] opened 2022-09-22 09:01 UTC
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.11.2.4516

* Which version of Visual Studio are you building with (if any)?
17.4.0 Preview 2 (VS Enterprise 2022 64-bit)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
1.0.0.18

* Which version of .NET are you building with?
4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
n/a

* Describe the problem and the steps to reproduce it.
heat fails to run, appears to be running from 64-bit MSBUILD.

Project build triggered by right clicking on project in Visual Studio and choosing "Build"

Output window contains
```
 Raytemp Blue Test Jig -> C:\Users\mike.hudgell\Source\Repos\ETI.BlueThermLE.ProductionSoftware\Raytem Blue Test Jig\bin\Release\Raytemp Blue Test Jig.exe 
Build started: Project: Bluetooth LE Production Installer, Configuration: Release x86   
C:\Program Files (x86)\WiX Toolset v3.14\bin\Heat.exe dir "..\Raytem Blue Test Jig\bin\Release" -cg RaytempFilesComponentGroup -dr dir_raytemp -sreg -srd -var var.Ras 6> Could not load file or assembly 'file:///C:\Program Files (x86)\WiX Toolset v3.11\bin\Heat.exe or one of its dependencies. An attempt was made to load a program with 6> at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackh 
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reciAssembly, StackCrawlMark
at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte() hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolez 6> at System.Reflection.Assembly.LoadFrom(String assemblyFile) 
at Microsoft.Tools.WindowsInstallerXml.Build.Tasks.WixToolTask.ExecuteToolThread(Object parameters) 
```
-----------------------------

At this point VS2022 crashes, so had to OCR a screenshot above

? is it possible to force vs to use 32-bit build for this project ?

* Describe the behavior you expected and how it differed from the actual behavior.

Project builds and produces MSI

**Comment by MikeAtETI** [comment] 2022-09-22 09:54
command line msbuild seems to suffer the same (and the msbuild.exe process also crashes) [this time I've added 3.14 to see if that helped]

```
Project "C:\Users\mike.hudgell\Source\Repos\ETI.BlueThermLE.ProductionSoftware\Bluetooth LE Instrument Production Softw
are.sln" (1) is building "C:\Users\mike.hudgell\Source\Repos\ETI.BlueThermLE.ProductionSoftware\Bluetooth LE Production
 Installer\Bluetooth LE Production Installer.wixproj" (11) on node 1 (default targets).
BeforeBuild:
  C:\Program Files (x86)\WiX Toolset v3.14\bin\Heat.exe dir "..\Raytem Blue Test Jig\bin\Release" -cg RaytempFilesCompo
  nentGroup -dr dir_raytemp -sreg -srd -var var.RayTemp.TargetDir -nologo -ag -nologo -out "C:\Users\mike.hudgell\Sourc
  e\Repos\ETI.BlueThermLE.ProductionSoftware\Bluetooth LE Production Installer\\Projects\RayTempInstallFiles.wxs"
  Could not load file or assembly 'file:///C:\Program Files (x86)\WiX Toolset v3.14\bin\Heat.exe' or one of its depende
  ncies. An attempt was made to load a program with an incorrect format.
     at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Run
  timeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean fo
  rIntrospection, Boolean suppressSecurityChecks)
     at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity,
   RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean
   forIntrospection, Boolean suppressSecurityChecks)
     at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashV
  alue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark&
  stackMark)
     at System.Reflection.Assembly.LoadFrom(String assemblyFile)
     at Microsoft.Tools.WindowsInstallerXml.Build.Tasks.WixToolTask.ExecuteToolThread(Object parameters)
```

```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'file:///C:\Program Files (x86)\WiX Toolset v3.14\bin\Heat.exe' or one of its dependencies. An attempt was made to load a program with an incorrect format.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.Tools.WindowsInstallerXml.Build.Tasks.WixToolTask.ExecuteToolThread(Object parameters)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by MikeAtETI** [comment] 2022-09-22 10:18
compiling the same wixproj in vs2019 works ok, so it does look like a bitness issue.

**Comment by robmen** [comment] 2022-09-22 11:42
Duplicate of #6636

**Closed by robmen** 2022-09-22 11:42 UTC
