### ISSUE TITLE
Google Chrome has blacklisted releases as malicious, won't allow downloads

### ISSUE THREAD

**Issue by face** [wixtoolset/issues#5465] opened 2016-12-30 18:06 UTC
## Bugs

Google has blacklisted the releases and won't allow downloads for some reason.    Till this is resolved i'm hesitant to circumvent Google's malware protection.     I guess I'll give building the latest release from source a go...

In the attached screenshot, you can see at the bottom Chrome refusing to download.
![screen shot 2016-12-30 at 8 00 29 am](https://cloud.githubusercontent.com/assets/25812/21570083/cdd8cd78-ce66-11e6-8a70-76a78c1ba68d.png)

**Comment by robmen** [comment] 2016-12-30 18:07
Duplicate of #5460

**Closed by robmen** 2016-12-30 18:07 UTC
Labels: external
