### ISSUE TITLE
Heat in WIXPROJ project causes VS2022 to crash

### ISSUE THREAD

**Issue by scottsteesy** [wixtoolset/issues#6699] opened 2022-01-05 22:07 UTC
I am moving to a new computer and installed VS2022, the latest Wix Toolset 3.11 and the brand new integration for VS2022.
I still have my old computer and I have a solution that includes a WIXPROJ project that builds fine in VS2019 on that machine.
I made an exact copy of the solution to the new machine, it opens fine in VS2022, but when building it immediately crashes VS, which restarts itself.
I had no idea what was going on until I opened a command prompt in the solution folder and used MSBuild on the solution.

The lines from the WIXPROJ are:

  <Target Name="BeforeBuild">
    <HeatDirectory NoLogo="$(HarvestDirectoryNoLogo)" SuppressAllWarnings="$(HarvestDirectorySuppressAllWarnings)" SuppressSpecificWarnings="$(HarvestDirectorySuppressSpecificWarnings)" ToolPath="$(WixToolPath)" TreatWarningsAsErrors="$(HarvestDirectoryTreatWarningsAsErrors)" TreatSpecificWarningsAsErrors="$(HarvestDirectoryTreatSpecificWarningsAsErrors)" VerboseOutput="$(HarvestDirectoryVerboseOutput)" AutogenerateGuids="$(HarvestDirectoryAutogenerateGuids)" GenerateGuidsNow="$(HarvestDirectoryGenerateGuidsNow)" OutputFile="HarvestedLicenses.wxs" SuppressFragments="$(HarvestDirectorySuppressFragments)" SuppressUniqueIds="$(HarvestDirectorySuppressUniqueIds)" Transforms="%(HarvestDirectory.Transforms)" Directory="D:\Build\Components\Licenses" ComponentGroupName="HarvestedLicenses" DirectoryRefId="LicensesDir" KeepEmptyDirectories="false" PreprocessorVariable="var.HarvestLicensesDir" SuppressCom="true" SuppressRootDirectory="true" SuppressRegistry="true" />
  </Target>

The output from MSBuild is:

Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 1/5/2022 4:14:22 PM.
Project "C:\Users\Scott\Source\Project.Install\Project.Install.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "C:\Users\Scott\Source\Project.Install\Project.Install.sln" (1) is building "C:\Users\Scott\Source\Project.Install\Project\Project.wixproj" (2) on node 1 (default targets).
BeforeBuild:
  C:\Program Files (x86)\WiX Toolset v3.11\bin\Heat.exe dir "D:\Build\Components\Licenses" -cg HarvestedLicenses -dr LicensesDir -scom -sreg -srd -var var.HarvestLicensesDir -ag -sfrag -out HarvestedLicenses.wxs
  Could not load file or assembly 'file:///C:\Program Files (x86)\WiX Toolset v3.11\bin\Heat.exe' or one of its dependencies. An attempt was made to load a program with an incorrect format.
     at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
     at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
     at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
     at System.Reflection.Assembly.LoadFrom(String assemblyFile)
     at Microsoft.Tools.WindowsInstallerXml.Build.Tasks.WixToolTask.ExecuteToolThread(Object parameters)

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'file:///C:\Program Files (x86)\WiX Toolset v3.11\bin\Heat.exe' or one of its dependencies. An attempt was made to load a program with an incorrect format.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.Tools.WindowsInstallerXml.Build.Tasks.WixToolTask.ExecuteToolThread(Object parameters)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Yet when I copy the seemingly bad command to notepad to remove the line breaks and quote the command, then paste it back to that same command prompt, so it looks like this:

"C:\Program Files (x86)\WiX Toolset v3.11\bin\Heat.exe" dir "D:\Build\Components\Licenses" -cg HarvestedLicenses -dr LicensesDir -scom -sreg -srd -var var.HarvestLicensesDir -ag -sfrag -out HarvestedLicenses.wxs

I get this output:

Windows Installer XML Toolset Toolset Harvester version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.

And I get the generated WXS file I expect.
Because of the the "file:///" at the beginning and the lack of quotes around the heat command's full path I would expect if the path were incorrect it would just give some kind of file not found error.
Yet it appears to attempt to run the correct EXE, so I am completely stumped as to why it fails from VS, let alone why it crashes VS.

**Comment by robmen** [comment] 2022-01-05 22:11
Almost certainly a duplicate of #6697 and #6692 and #6636.

If not, please add a link to a GitHub repo with your .sln and projects that reproduce the problem.

**Closed by robmen** 2022-01-05 22:11 UTC
Labels: triage

**Comment by scottsteesy** [comment] 2022-01-06 15:52
I searched the bugs looking for same issue before submitting mine and found nothing, but I think that is because it defaulted to open bugs and all those are closed.
But they do all have the same root cause, and I eventually found the solution in a comment in one of the bugs, though that comment wasn't flag as an answer.
It is too bad they are closed when this issue continues to occur.
Seems like the easy answer would be to make Heat.exe a native EXE so MSBuild would never attempt to load it in process ... even if that means Heat.exe was just a relay to a managed program.
BTW, some answers said (we) should be using the HeatDirectory target directly, but my projects go back to before heat existed and added Heat when it was brand new and the instructions to use it were followed exactly. Took me a while to find the newer "correct" way to use heat, but the HarvestDirectory target doesn't seem to have all the parameters I need, and it has a side effect of automatically adding stuff to the build which I do NOT want ... I often use heat to gather info for files that feed into another step instead of to make a WXS to include in the build. Also, in another solution I have one project that does a bunch of different harvests that do produce WXS files, but that project does nothing else, there are 6 other projects that all use the resulting WXS files. This was done so that the harvest only occurs once for each directory instead of 6 times and guarantees they will all include exactly the same list of files.

**Comment by rseanhall** [comment] 2022-01-06 16:02
> Seems like the easy answer would be to make Heat.exe a native EXE so MSBuild would never attempt to load it in process ... even if that means Heat.exe was just a relay to a managed program.

This is not true. The root cause is that the WiX build task is trying to run Heat inside the MSBuild process in order to save the time required to spin up a new process. The easy answer for people calling `HeatDirectory` directly is to add the parameter to force it to run out of process. The next easier answer is for MSBuild to allow your project to force `HeatDirectory` to be x86 (https://github.com/dotnet/msbuild/issues/5541). This issue could have been fixed in v3 by changing wix.targets (by setting the architecture on the `UsingTask`), but that wouldn't help everyone using 3.11.2 and this isn't important enough to create a 3.11.3. This is not an issue in v4.
