### ISSUE TITLE
Wix Toolset Visual Studio 2015 Extension - Unable to open "Tool Settings"

### ISSUE THREAD

**Issue by hypetsch** [wixtoolset/issues#5540] opened 2017-03-21 15:36 UTC
Configuring "Tool Settings" in project properties of my WiX project is not possible.

![image](https://cloud.githubusercontent.com/assets/16302578/24155199/71736c00-0e53-11e7-925f-8b2d1fe4bc38.png)

Visual Studio 2015 Update 3
WiX Toolset v3.11.0.1507
WiX Toolset Visual Studio Extension version 0.9.10.21458

**Comment by hypetsch** [comment] 2017-03-21 16:18
The same problem occurs when trying to open the settings in VS2017:

An error occurred trying to load the page.
Class not registered.
Looking for object with CLSID: {37DA98B6-C5F4-4CE6-867F-553EBE590ABE}.

**Comment by robmen** [comment] 2017-03-21 16:21
Duplicate of #5519

**Closed by robmen** 2017-03-21 16:21 UTC
Labels: duplicate
