### ISSUE TITLE
The ProgressText of Msi is not shown correctly.

### ISSUE THREAD

**Issue by gfnba123** [wixtoolset/issues#5789] opened 2018-03-31 08:23 UTC
> _Version of WiX_: **v3.10.3.3007**

> _Windows system_: **Windows10 enterprise (64bit)**

> _Version of msiexec_: **Windows Installer. V 5.0.15063.0.**

* Describe the behavior you expected and how it differed from the actual behavior.

>[https://i.stack.imgur.com/kLD9Z.png](https://i.stack.imgur.com/kLD9Z.png)

As shown in the figure, the text" copied new files "above the progress bar shows "File: [1], Directory: [9], Size: [6] "such redundant text.

This is not the case on other versions of the system.

**Comment by barnson** [comment] 2018-03-31 14:46
Duplicate of https://github.com/wixtoolset/issues/issues/5423.

**Closed by barnson** 2018-03-31 14:46 UTC
Labels: duplicate
