### ISSUE TITLE
Incorrect WixTasksPath setting in Visual Studio 2017 extension

### ISSUE THREAD

**Issue by JaapMosselman** [wixtoolset/issues#5514] opened 2017-03-08 08:41 UTC
If this issue is a bug:

* Which version of WiX are you building with?

> 3.10.3.3007

* Which version of Visual Studio are you building with (if any)?

> 2017 RTM

* Which version of .NET are you building with?

> 4.0

* Describe the problem and the steps to reproduce it.

> Build error when build a custom actions project because it can't find the WixTasks.dll. This is caused by the fact that Visual Studio 2017 is now installed in a different folder structure. So in C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix.ca.targets the WixTasksPath is set to a wrong location. It is now $(MSBuildExtensionsPath32)\\..\WiX Toolset v3.10\bin\WixTasks.dll. When I change it to $(MSBuildProgramFiles32)\WiX Toolset v3.10\bin\WixTasks.dll al works fine.

* Describe the behavior you expected and how it differed from the actual behavior.

> Compiling correctly

**Comment by robmen** [comment] 2017-03-08 08:44
This is a duplicate of #5513.

**Closed** 2017-03-08 15:00 UTC
Labels: duplicate

**Comment by robmen** [comment] 2017-03-08 17:28
@rseanhall I was leaving this one open so that people searching would find it. Let's see if another duplicate gets opened now that there is more a bit more information about the dependency on v3.11 RC.

**Comment by rseanhall** [comment] 2017-03-08 17:35
That was a good idea. I didn't think about that it would deter people from making more duplicates if it was the near the top of the list.

**Comment by JaapMosselman** [comment] 2017-03-08 17:58
Yeah, that's indeed the reason I missed #5513. Didn't think about it to look at closed issues first.
Beside that the references in the target file is incorrect, are there other issues which require 3.11 to get customaction working? It now compiles just fine, but have not yet tested the installation.
