### ISSUE TITLE
Burn should use user UI language for localization instead of formatting language

### ISSUE THREAD

**Issue by jozefizso** [wixtoolset/issues#5285] opened 2016-05-02 14:56 UTC
- Which version of WiX are you building with?

> WiX 3.10.2
- Which version of Visual Studio are you building with (if any)?

> Visual Studio 2015 Update 2
- Which version of .NET are you building with?

> .NET 4.6
- Describe the problem and the steps to reproduce it.

> I created localized bootstrapper application. I use Windows 10 with English UI and Slovak regional (date/time) formatting. When I run the installer created with burn bootstrapper it is displayed in Slovak language.
- Describe the behavior you expected and how it differed from the actual behavior.

> As I have the English user interface language selected in Windows, the burn bootstapper should use the English localization file.
## Feature proposal

I think users expect to have applications localized based on the UI language. Current burn behavior is different from other Windows applications because it uses date/time formatting language to load localization files.

Also new variable `UserUILanguageID` should be available to the burn engine that will get it's value from the `GetUserDefaultUILanguage()` function so installation authors can have access to both UI and formatting languages.

| Burn variable | Win32 function |
| --- | --- |
| `UserLanguageID` | `GetUserDefaultLangID()` |
| `UserUILanguageID` | `GetUserDefaultUILanguage()` |

Simillar issue: #3922

**Comment by barnson** [comment] 2016-05-02 15:46
Mostly a dupe of https://github.com/wixtoolset/issues/issues/4499.

**Comment by jozefizso** [comment] 2016-05-02 16:32
Do you plan to integrate the wix3#275 pull request to 3.10 or 3.11 release?

**Comment by barnson** [comment] 2016-05-03 23:59
v3.11

**Comment by barnson** [comment] 2016-05-04 17:12
Keeping open for the variable suggestion.

**Comment by BMurri** [comment] 2017-03-06 16:13
This was fixed in [wix3](https://github.com/wixtoolset/wix3/commit/cda30f74c8d77e2e2d6d514401de9588feab210d).

Here is the pull request for [wix4](https://github.com/wixtoolset/wix4/pull/236)

**Closed** 2017-08-21 01:07 UTC
Labels: enhancement, WixStdBA
