### ISSUE TITLE
wix-4.0.0-rc.2 : System.ArgumentOutOfRangeException: Index and length must refer to a location within the string

### ISSUE THREAD

**Issue by ronfluegge** [wixtoolset/issues#7192] opened 2023-02-02 07:03 UTC
Which version of WiX are you building with?
wix-4.0.0-rc.2

Which version of Visual Studio are you building with (if any)?
Visual Studio 2022(17.4.4)

Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
Heatwave for VS 2022 V. 0.9.4

Which version of .NET are you building with?
.Net Framework 4.8

If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
N/A

Describe the problem and the steps to reproduce it.

Converted a working WIX V3 to V4 and compiled

8>------ Rebuild All started: Project: ServerDropDown, Configuration: Release Any CPU ------
8> ServerDropDown -> D:\Server Names2005\DropdownList\bin\Release\SetupConsole.exe
9>------ Rebuild All started: Project: DEServerSetupInstall_wix, Configuration: Release x86 ------
9>wix.exe : error WIX0001: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
9>Done building project "DEServerSetupInstall_wix.wixproj" -- FAILED.
========== Rebuild All: 8 succeeded, 1 failed, 0 skipped ==========

Compiled solution as release
wix.exe : error WIX0001: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.  
File:  WIX.EXE ... Line:  1

**Comment by robmen** [comment] 2023-02-02 13:52
Duplicate of #7181

**Closed by robmen** 2023-02-02 13:52 UTC
Labels: duplicate
