### ISSUE TITLE
WiX Toolset requires the .NET Framework 3.5.1 Windows feature to be enabled.

### ISSUE THREAD

**Issue by JanZeman** [wixtoolset/issues#5534] opened 2017-03-16 18:12 UTC
## Feature requests

I was very much surprised by this message: "WiX Toolset requires the .NET Framework 3.5.1 Windows feature to be enabled." It appeared on my freshly installed Windows 10 machine. This old framework is not present (preinstalled) on the current Windows systems. Would not fix be a very simple by re-targeting your builds to a newer frameworks?

Thanks for consideration
Jan

**Comment by robmen** [comment] 2017-03-16 18:15
Dupe of #5523, backwards compatibility is a b***h. Also: https://www.firegiant.com/blog/2017/3/14/wix-online-meeting-123-highlights/

**Closed by robmen** 2017-03-16 18:15 UTC
Labels: duplicate

**Comment by JanZeman** [comment] 2017-03-16 18:27
OK, I checked the opened issues but did not notice this one. Cool, thank you.

**Comment by eabase** [comment] 2020-11-02 11:56
This is an absurd requirement in this day and age. 
There's simply no way I'm going back to that old MS crap of .NET < 4.x. (I left that era 5 years ago.)

> backwards compatibility is a b***h.

Not if you do it properly. Provide installer detection for old shit.

**Comment by rseanhall** [comment] 2020-11-02 12:57
With that offensive and abusive comment, there's clearly not going to be any more productive discussion on this issue.
