### ISSUE TITLE
FIPS flag does not seem to be working

### ISSUE THREAD

**Issue by iofacture** [wixtoolset/issues#6428] opened 2021-04-14 22:14 UTC
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.11.1.2318

* Which version of Visual Studio are you building with (if any)?
None - this is happening on our build server
Windows Server 2016

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
None, please see above

* Which version of .NET are you building with?
.NET Framework 4.7

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
N/A

* Describe the problem and the steps to reproduce it.
When we enable/enforce Windows Server 2016 Local Security Policy entitled:
System Cryptography: Use FIPS compliant algorithms for encryption, hashing, and signing

The build breaks with the following error:
System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

The candle.exe directive we are using does have the -fips flag on it after adding the following to the project file:
```
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
    <FipsCompliant>true</FipsCompliant>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
    <FipsCompliant>true</FipsCompliant>
  </PropertyGroup>
```

However the build only continues to that point when we have the security policy turned off.  When we turn it back on the build breaks with that exception before it is allowed to build the wix project.

* Describe the behavior you expected and how it differed from the actual behavior.

When we added the FipsCompliant property to the wix project file, we expected the build to continue and succeed with the FIPS security policy enabled.  However, instead, regardless of any configuration, the build breaks with the following exception:
System Cryptography: Use FIPS compliant algorithms for encryption, hashing, and signing

**Comment by rseanhall** [comment] 2021-04-14 22:21
Duplicate of https://github.com/wixtoolset/issues/issues/5672. It's fixed in v3.14 and v4.0.

**Closed by rseanhall** 2021-04-14 22:21 UTC
Labels: triage

**Comment by iofacture** [comment] 2021-04-15 15:21
Excellent.  Any projected release date for v3.14 and v4.0?

**Comment by iofacture** [comment] 2021-04-15 15:23
According to your website, only 3.11.2 is available
https://wixtoolset.org/releases/
