### ISSUE TITLE
ProgressDlg shows "Copying new files File: [1], Directory: [9], Size: [6]" on Windows 10

### ISSUE THREAD

**Issue by eteeuw-groeneveld** [wixtoolset/issues#5697] opened 2017-10-09 07:59 UTC
* Which version of WiX are you building with?

> 3.11.0.1701

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2017 Professional (15.3.5)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.21.62588

* Which version of .NET are you building with?

>4.6.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 Enterprise 1703 x64

* Describe the problem and the steps to reproduce it.

> Create a WiX Setup project (MSI) and use the WixUI_FeatureTree dialog set. Do NOT reference the WixUI_ErrorProgressText. Run the setup on Window 8.1 or below and the ProgressDlg will show 'Copying new files' correctly. Run the setup on Windows 10 (1703?) and the ProgressDlg will show 'Copying new files File: [1], Directory: [9], Size: [6]' instead.

* Describe the behavior you expected and how it differed from the actual behavior.

>  The ProgressDlg should show 'Copying new files' instead of 'Copying new files File: [1], Directory: [9], Size: [6]' on Windows 10 as well (using stock action text).

**Comment by BMurri** [comment] 2017-10-09 08:48
Looks to me to be a duplicate of #5423

**Comment by eteeuw-groeneveld** [comment] 2017-10-09 09:51
I agree. I've searched for similar issues, but didn't this one. Why is that issue closed?

**Comment by barnson** [comment] 2017-10-09 14:36
When you don't reference WixUI_ErrorProgressText, WiX doesn't supply any strings. Windows is supplying and failing to correctly format the strings. Nothing WiX can do to influence that, other than supply the strings.

**Closed** 2019-02-09 05:13 UTC
Labels: external
