### ISSUE TITLE
Util.wixext provides custom action binaries for ARM only

### ISSUE THREAD

**Issue by wjk** [wixtoolset/issues#6216] opened 2020-07-16 02:47 UTC
## Bugs

* Which version of WiX are you building with?
  > `WixToolset.Sdk` 4.0.0-build-0143
  > `WixToolset.Util.wixext` v4.0.45
  > `WixToolset.UI.wixext` v4.0.7
  > `WixToolset.Data` v4.0.81

* Which version of Visual Studio are you building with (if any)?
  > Visual Studio 2019, 16.7.0 preview 3.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
  > 1.0.0.4, although it isn’t yet compatible with WiX 4

* Which version of .NET are you building with?
  > 4.8.04161

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
  > Windows 10 version 2004, build 20150.1000

* Describe the problem and the steps to reproduce it.
  > Build a project that uses the above WiX versions and that contains a `<util:EventManifest>` element. I am using configuration Debug and platform x86. During installation, msiexec yields error 1723.
  >
  > Investigation reveals that the only provided copy of `utilca.dll` is compiled for ARM. No x86/x64 (or ARM64) binaries are present. This can be independently confirmed by extracting the wixlib zip file from the extension DLL, extracting `utilca.dll` from that, and running `dumpbin.exe /nologo /headers utilca.dll`. I do not know if this issue affects other WiX extensions that include custom actions as well.

* Describe the behavior you expected and how it differed from the actual behavior.
  > A package built for x86 platform should install on an Intel-based machine, and reference no ARM binaries.

As an aside, when I add `<UIRef Id="WixUI_Minimal" />` to my wxs file, the WiX compiler yields error WIX94 (“The identifier 'WixUI:WixUI_Minimal' could not be found.”). I don't know if this is caused by a similar issue to the custom action bug described above. Thanks!

**Comment by rseanhall** [comment] 2020-07-16 02:58
I don't want to discourage you from trying out the bleeding edge of v4, but we haven't documented how to use these versions of WiX because they are not ready for public consumption as you are seeing. Are you planning on helping us fix these kind of issues?

**Comment by wjk** [comment] 2020-07-16 03:00
@rseanhall If I can get an occasional bit of help where needed, certainly! FWIW I’ve already submitted improvements to WiX 4, namely https://github.com/wixtoolset/Netfx.wixext/pull/11. Thanks!

**Comment by rseanhall** [comment] 2020-07-16 03:15
We're having problems with bind paths - https://github.com/wixtoolset/issues/issues/6200. You'll have to get on [wix-devs](https://wixtoolset.org/documentation/mailinglist/) for any help you might need. I don't know if anyone has started working on that.

The UI extension has not been updated since major breaking changes were made. Rob's working on that one - https://github.com/wixtoolset/UI.wixext/pull/5.

Although... are you sure you're referencing the UI extension properly? I would expect Core to complain that it couldn't load the extension or that the code from the out of date extension is corrupt.

**Comment by robmen** [comment] 2020-07-16 04:51
This is almost certainly a dupe of #6200. I tried creating a quick unit test to reproduce it and was not successful. I'm finishing the set of bugs building UI.wixext exposed and #6200 is (currently) at the tail of that trail.

**Comment by rseanhall** [comment] 2020-07-16 11:21
I was able to create a failing test for #6200. If you want to fix the problem here in Util.wixext, it's that the x86 bind path is getting set to a Win32 directory but the x86 dll is getting built into an x86 directory.

> -bindPath x86=C:\src\mynewwix4\Util.wixext\build\Release\Win32

**Closed** 2020-07-17 09:30 UTC
