### ISSUE TITLE
WiXUI attribute to omit EULA dialog

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#7116] opened 2022-12-24 06:05 UTC
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

It would be nice if the WixUI element had an attribute that caused the EULA dialog to be omitted.  At that point the WiX Print EULA CA should be omitted also.  This would result in package generation that is smaller and contains no custom actions.  For WiXUI_Minimal the controls should be disabled and license agreement not required to install.

* Describe how you're accomplishing the feature today (if possible).

Today I add Publish events to cause the dialog to be bypassed.  But this leaves bloat in the MSI and takes advanced knowledge of MSI to know how to implement this.

* Describe what you'd like the new feature to do.

Add an attribute to the WiXUI element such as ShowEULADialog="yesnotype"  default yes if omitted for backwards compatibility.

**Comment by barnson** [comment] 2023-05-16 17:47
Dupe of https://github.com/wixtoolset/issues/issues/3072.

**Closed by barnson** 2023-05-16 17:47 UTC
Labels: enhancement, wixui
