### ISSUE TITLE
Page Not Found: /docs/fourthree_bundles/

### ISSUE THREAD

**Issue by dal958** [wixtoolset/issues#7293] opened 2023-03-22 05:01 UTC
### WiX Toolset Page URL

https://wixtoolset.org/docs/fourthree_bundles/

### Page URL that linked to WiX Toolset

https://github.com/wixtoolset/issues/issues/7292

**Comment by robmen** [comment] 2023-03-22 05:08
Duplicate of #7292

**Closed by robmen** 2023-03-22 05:08 UTC
Labels: duplicate
