### ISSUE TITLE
wix 3.11.2 in windows 11 with visual studio 2022 64bit not work

### ISSUE THREAD

**Issue by alqmar-smeup** [wixtoolset/issues#6692] opened 2021-12-28 14:21 UTC
hi, i've created a new virtual machine with windows 11 and wix 3.11.2 and visual studio 2022 64bit, but a my exist project doesn't work. Visual Studio 2022 crash before to start wix project compilation.

If i open this project in my old virtual machine with windows 10 and visual studio 2019 32bit and wix 3.11.1 works correctly.

**Comment by robmen** [comment] 2021-12-28 14:28
Not much to go on here. Please consider adding a link to a GitHub repo with your .sln and projects that reproduce the problem.

**Comment by alqmar-smeup** [comment] 2021-12-28 14:37
Ok, i'll prepare a simple example, becouse this project i cannot shared.

**Comment by alqmar-smeup** [comment] 2021-12-28 15:15
[Plain.Poc.WixSample.zip](https://github.com/wixtoolset/issues/files/7785281/Plain.Poc.WixSample.zip)

**Comment by rseanhall** [comment] 2021-12-28 15:34
Duplicate of https://github.com/wixtoolset/issues/issues/6636.

**Closed by rseanhall** 2021-12-28 15:34 UTC
Labels: triage
