### ISSUE TITLE
MakeSfxCA.exe fails when custom actions references System.Net

### ISSUE THREAD

**Issue by darrensteadman** [wixtoolset/issues#5668] opened 2017-08-23 14:05 UTC
* Which version of WiX are you building with?

3.11.0.1701

* Which version of Visual Studio are you building with (if any)?

VS 2017 15.3.2

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

0.9.21.62588

* Which version of .NET are you building with?

.NET 4.6.1

* Describe the problem and the steps to reproduce it.

When I try and build a custom action that references System.Net I get the following error when building

> EXEC : error : System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extesions\net461\lib\System.Net.Sockets.dll'.
> at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
> at System.IO.File.GetAttributes(String path)
> at Microsoft.Deployment.Compression.ArchiveFileStreamContext.OpenFileReadStream(String path, FileAttributes& attributes, DateTime& lastWriteTime)
> at Microsoft.Deployment.Compression.Cab.CabPacker.Pack(IPackStreamContext streamContext, IEnumerable`1 files, Int64 maxArchiveSize)
> at Microsoft.Deployment.Compression.Cab.CabEngine.Pack(IPackStreamContext streamContext, IEnumerable`1 files, Int64 maxArchiveSize)
> at Microsoft.Deployment.Compression.CompressionEngine.Pack(IPackStreamContext streamContext, IEnumerable`1 files)
> at Microsoft.Deployment.Compression.ArchiveInfo.PackFileSet(String sourceDirectory, IDictionary`2 fileNames, CompressionLevel compLevel, EventHandler`1 progressHandler)
> at Microsoft.Deployment.Tools.MakeSfxCA.MakeSfxCA.PackInputFiles(String outputFile, IDictionary`2 fileMap)
> at Microsoft.Deployment.Tools.MakeSfxCA.MakeSfxCA.Build(String output, String sfxdll, IList`1 inputs, TextWriter log)
> at Microsoft.Deployment.Tools.MakeSfxCA.MakeSfxCA.Main(String[] args)

It would appear to be happening when running MakeSfxCA.exe. The interesting thing is if you look at the path it is looking for there is a spelling mistake. The path it is looking for is Microsoft.NET.Build.Extesions where as it should be Microsoft.NET.Build.Extensions (notice the missing 'n')

If I do a clean build then it fails every time however once it has failed if I then do another build (not rebuild) then it works.

**Comment by darrensteadman** [comment] 2017-08-23 14:23
I've investigated some more and found that since an update we recently did we are now referencing a net461 assembly that references a .netstandard2.0 assembly. If I remove the dependency and thus remove the dependency on netstandard2.0 everything works as expected.

**Comment by barnson** [comment] 2017-08-24 00:14
Appears to be duplicate of https://github.com/wixtoolset/issues/issues/4688.

**Closed** 2017-08-31 16:48 UTC
Labels: duplicate
