### ISSUE TITLE
Wix 3.11 not available on nuget.org

### ISSUE THREAD

**Issue by zplan** [wixtoolset/issues#5579] opened 2017-05-10 06:05 UTC
## Feature requests

If this issue is a feature request:

* Describe what you'd like the new feature to do.

> Download of new versions should be available on nuget.org as a nuget package. There are always 'unoffical' nuget packages from people who have the same problem. Please provide the package as soon as a release is stable.

**Comment by letmaik** [comment] 2017-05-24 14:29
Why is this added to the v4.0 milestone? The package should have been released on nuget three weeks ago. Right?

**Comment by robmen** [comment] 2017-05-24 17:35
There is no WiX v3.x NuGet package. The work is being done in WiX v4.

**Comment by letmaik** [comment] 2017-05-24 18:19
https://www.nuget.org/packages/WiX I guess it's unofficial, but very useful!

**Comment by letmaik** [comment] 2017-05-24 21:27
Nevermind, the maintainer uploaded 3.11.

**Comment by robmen** [comment] 2021-01-06 09:51
Duplicate of #3981

**Closed by robmen** 2021-01-06 09:51 UTC
Labels: FourOhPreviewZero, wixsetup
