### ISSUE TITLE
VS 2022 crashes with GitVersionTask

### ISSUE THREAD

**Issue by EMostafaAli** [wixtoolset/issues#6694] opened 2021-12-29 18:20 UTC
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> Wix 3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

> Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.18

* Which version of .NET are you building with?

> .NET 4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> NA

* Describe the problem and the steps to reproduce it.

> There is a particular WIX project that won't load in Visual Studio 2022. The same project works fine with 2019. From EventViewer I got the following log

`Application: devenv.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.BadImageFormatException at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean) at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean) at System.Reflection.RuntimeAssembly.InternalLoadFrom(System.String, System.Security.Policy.Evidence, Byte[], System.Configuration.Assemblies.AssemblyHashAlgorithm, Boolean, Boolean, System.Threading.StackCrawlMark ByRef) at System.Reflection.Assembly.LoadFrom(System.String) at Microsoft.Tools.WindowsInstallerXml.Build.Tasks.WixToolTask.ExecuteToolThread(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart(System.Object) `

Other projects loads fine in VS2022 so I hunted down the culprit part and I found that if I remove the following section from wixproj the tool works fine.

```
<Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
	<PropertyGroup>
		<ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
	</PropertyGroup>
	<Error Condition="!Exists('..\packages\GitVersionTask.5.3.7\build\GitVersionTask.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\GitVersionTask.5.3.7\build\GitVersionTask.props'))" />
	<Error Condition="!Exists('..\packages\GitVersionTask.5.3.7\build\GitVersionTask.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\GitVersionTask.5.3.7\build\GitVersionTask.targets'))" />
</Target>
<Import Project="..\packages\GitVersionTask.5.3.7\build\GitVersionTask.targets" Condition="Exists('..\packages\GitVersionTask.5.3.7\build\GitVersionTask.targets')" />
```

* Describe the behavior you expected and how it differed from the actual behavior.

> The project should load in VS2022 as it loads in VS2019

**Comment by barnson** [comment] 2021-12-30 05:08
Does VS crash on load or on build? Are you using heat? Please attach the .wixproj so we have some context.

**Comment by EMostafaAli** [comment] 2021-12-30 14:39
It crashes on load. There is a heat task but it is irrelevant (at least this what I believe).
I attached the wixproj file but please notice:

- I am aware of the heat issue related to run as a separate process and it is not the source of my issue
- In the wixproj, if you remove the section mentioned above the project will load (the issue won't happen) 

[Installer.zip](https://github.com/wixtoolset/issues/files/7793187/Installer.zip)

**Comment by robmen** [comment] 2021-12-30 14:48
Duplicate of #6636 due to line 69.

**Closed by robmen** 2021-12-30 14:48 UTC
Labels: duplicate

**Comment by EMostafaAli** [comment] 2021-12-30 15:16
@robmen , Please read my comments above carefully. This is different from #6636 
Mine crashes on loading the project (not building) and adding RunWixToolsOutOfProc="True" didn't solve the issue. Please see attached file.
[Installer_v2.zip](https://github.com/wixtoolset/issues/files/7793544/Installer_v2.zip)

**Comment by robmen** [comment] 2021-12-30 15:21
I read your comments but the project example you sent did not include the out of proc settings. That made it a duplicate issue. You should not directly reference Tasks (such as `HarvestDirectory`) out of someone else's targets.

Consider providing a link to a public GitHub repo that reproduces the issue without directly referencing WiX Tasks.
