### ISSUE TITLE
Support for Ratina display in themes for Logo & LogoFile

### ISSUE THREAD

**Issue by dotriz** [wixtoolset/issues#6155] opened 2020-04-16 14:53 UTC
I have built a setup in VS 2019 with WiX Toolset 3.11.1.2318
I am using **LogoFile** & **LogoSide** which works fine in Windows 10. But if the setup is used on Ratina display, image doesn't appear crisp. Is there any way I can use 2x version of these files in the setup? Right now, if I use 2x version of images, they will cut in setup. Here is how I have used it 

`<BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.HyperlinkSidebarLicense">
      <bal:WixStandardBootstrapperApplication LogoFile="Resources/Sidebar.png" ThemeFile="Resources/ClassicTheme.xml" LocalizationFile="Resources/ClassicTheme.wxl" LicenseUrl="" />
    </BootstrapperApplicationRef>`

**Comment by barnson** [comment] 2020-04-29 23:18
Duplicate: https://github.com/wixtoolset/issues/issues/3920

**Comment by rseanhall** [comment] 2020-07-05 09:54
This is not a duplicate. In order to avoid rescaling an image, there needs to be a way to provide multiple resolutions of the same image to thmutil.

**Comment by BMurri** [comment] 2020-07-07 22:22
The "native windows" way to provide multiple resolutions is via an ICON. Better yet from a pure engineering view is SVG, if we can handle those.

**Comment by rseanhall** [comment] 2020-07-07 22:27
In that case, maybe this is a duplicate of https://github.com/wixtoolset/issues/issues/4655.

**Comment by rseanhall** [comment] 2021-06-04 19:45
There were two things to address here. The first was to use the actual dimensions of the source image when drawing it instead of using the control's current width and height. This allows specifying a single high resolution image, which will be downscaled if necessary. But it also means that now there is always the potential for thmutil to scale an image to a different aspect ratio than the original, even if using the method below.

The other thing was to allow specifying multiple resolutions for the same image. This gives people the flexibility to avoid scaling if they don't like thmutil's quality of scaling. This will require a custom theme, though.

**Closed** 2021-06-04 19:57 UTC
Labels: WixStdBA, nativesdk
