### ISSUE TITLE
Wix Project Properties > Paths. all labels not shown

### ISSUE THREAD

**Issue by YoungjaeKim** [wixtoolset/issues#5792] opened 2018-04-06 11:08 UTC
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> v4.0.0.5918 

* Which version of Visual Studio are you building with (if any)?

> VS 2017 15.6.5

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.21.62588

* Which version of .NET are you building with?

> 4.6.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 1709

* Describe the problem and the steps to reproduce it.

> see attached image

* Describe the behavior you expected and how it differed from the actual behavior.

> cannot read paths labels. Possibly, its color is same as background.

![image](https://user-images.githubusercontent.com/1265284/38418034-ac6ac656-39d5-11e8-8b5c-c98db4809644.png)

**Comment by barnson** [comment] 2018-04-12 02:54
Duplicate of https://github.com/wixtoolset/issues/issues/4286

**Closed by barnson** 2018-04-12 02:54 UTC
Labels: duplicate
