### ISSUE TITLE
error LGHT0001: Failed to compare two elements in the array., Facing this error in all V4 versions.

### ISSUE THREAD

**Issue by RajagurunathanManikandan** [wixtoolset/issues#6760] opened 2022-04-07 10:25 UTC
Hi @robmen , @Gerolkae , @fourpastmidnight , @wixbot , @SonnyAD   

I'm still facing this issue("error LGHT0001: Failed to compare two elements in the array") in the below versions.
- wix-4.0.2719.0
- wix-4.0.0.5918
- wix-4.0.0.5512
- wix-4.0.0.5205
- wix-4.0.0.5204
- wix-4.0.0.4506
- wix-4.0.0.4305
- wix-4.0.0.3922
- wix-4.0.0.3826
- wix-4.0.0.3729
- wix-4.0.0.3430
- wix-4.0.0.3226
- wix-4.0.0.2926
- wix-4.0.0.2603
- wix-4.0.0.2220
- wix-4.0.0.2115
- wix-4.0.0.2102
- wix-4.0.0.1726
- wix-4.0.0.1621
- wix-4.0.0.1320
- wix-4.0.0.1216
- wix-4.0.0.1210
- wix-4.0.0.1203
- wix-4.0.0.1015
- wix-4.0.0.1007
- wix-4.0.0.0701
- wix-4.0.0.0424
- wix-4.0.0.0012
- wix-4.0.0.0004

error snap:
![image](https://user-images.githubusercontent.com/84576346/162176657-f5a74fbf-f22d-46e7-a442-70650589d40b.png)

Can you share the latest V4.0 download link which doesn't have this issue?
Thanks in advance.

**Comment by robmen** [comment] 2022-04-07 11:28
Duplicate of #4563

**Closed by robmen** 2022-04-07 11:28 UTC
Labels: triage
