### ISSUE TITLE
"Exclude from Project" doesn't seem to work in VS 2022 w/ Heatwave

### ISSUE THREAD

**Issue by SJFriedl** [wixtoolset/issues#8883] opened 2024-12-28 20:48 UTC
### WiX Version

5.0.2

### .NET or MSBuild or Visual Studio Version

.NET 9.0.101

### HeatWave Version

1.0.4.5

### Windows Version

Win11 24H2

### Repro Steps

1. Ensure the latest of everything (Visual Studio, Windows, Wix, Heatwave)
2. Create an "MSI Package" product in Visual Studio; I call it `Setup`
3. In the Solution Explorer, right-click on a file (say, `Folders.wxs`) and select "Exclude from Project"
4. Observe that the `Setup.wixproj` file now includes the "Compile Remove" clause in the XML
5. Observe that `Folders.wxs` is still present in the project

![image](https://github.com/user-attachments/assets/1dbfb7bf-198f-46c2-ba91-113d667533c2)

### Actual Result

Actual result: the "Exclude from Project" operation does not exclude the file from the project.

It doesn't throw any errors, it **does** add 
```
<ItemGroup>
    <Compile Remove="Folders.wxs" />
</ItemGroup>
```
to the `Setup.wixproj` file, but the file remains visible in Solution Explorer under the project and is clearly participating in the project (verified by adding an obvious syntax error to the file and rebuilding).

Curiously, repeating the "Exclude from Project" operation adds additional and duplicate `<ItemGroup>` stanzas to the project file.

![image](https://github.com/user-attachments/assets/87570f46-caf9-4fc1-b04b-372e5b1e8a06)

### Expected Result

I expected the file to be excluded from the project.

Workaround: manually **delete** the file to remove it from the project entirely.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by robmen** [comment] 2024-12-28 20:52
Duplicate of #7687

**Closed by robmen** 2024-12-28 20:52 UTC

**Comment by SJFriedl** [comment] 2024-12-28 21:08
Thank you; I really did make an effort to find an existing issue, but I'm new to the project and don't know my way around very well.
