### ISSUE TITLE
Application Shortcut has arrows added to it after updating from WiX 3.9.1208.0 (R2) to WiX 3.10.2.2516

### ISSUE THREAD

**Issue by scottgshin** [wixtoolset/issues#5312] opened 2016-06-01 16:44 UTC
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.10.2.2516

* Which version of Visual Studio are you building with (if any)?

> VS2013 12.0.40629.00 Update 5

* Which version of .NET are you building with?

> 4.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> 10

* Describe the problem and the steps to reproduce it.

> After updating from WiX 3.9.1208.0 (R2) to 3.10.2.2516, I rebuilt to make sure there were not any problems.  Upon installing the shortcut placed on the desktop and in the start menu for the program has two arrows added to the icon. I use the same icon for another shortcut to a data directory and it does not have the arrows added.

* Describe the behavior you expected and how it differed from the actual behavior.

> I expect the icon to be the same throughout.

![image](https://cloud.githubusercontent.com/assets/13341486/15717800/7576f5c2-27dd-11e6-93a5-5bb443c93e40.png)

**Comment by rseanhall** [comment] 2016-06-01 16:52
Duplicate of https://github.com/wixtoolset/issues/issues/5251

**Closed by rseanhall** 2016-06-01 16:52 UTC
