### ISSUE TITLE
light.exe crashes with LGHT0001 : Item has already been added

### ISSUE THREAD

**Issue by archiecobbs** [wixtoolset/issues#5443] opened 2016-11-28 19:44 UTC
* Which version of WiX are you building with?

3.10.3.3007

* Which version of Visual Studio are you building with (if any)?

None. I'm building using the java fx packager, which uses WiX.

* Which version of .NET are you building with?

Not sure. I think 4.6.1. This build is on a Windows 7 machine.

* Describe the problem and the steps to reproduce it.

Running `light.exe` generates this error:
```
light.exe : error LGHT0001 : Item has already been added. Key in dictionary: 'reg27C770ACE19E5E293FBC5389256D52D0'  Key being added: 'reg27C770ACE19E5E293FBC5389256D52D0'

Exception Type: System.ArgumentException

Stack Trace:
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at Microsoft.Tools.WindowsInstallerXml.Binder.SetComponentGuids(Output output)
   at Microsoft.Tools.WindowsInstallerXml.Binder.BindDatabase(Output output, String databaseFile)
   at Microsoft.Tools.WindowsInstallerXml.Binder.Bind(Output output, String file)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Light.Run(String[] args)
```

When I inspect the `.wixobj` file, you can see the duplicate entries:
```
...
      <row sourceLineNumber="C:\Users\Archie Cobbs\AppData\Local\Temp\fxbundler762063117289376751\windows\RDTiffDefinition.dll.wxi*12|C:\Users\Archie Cobbs\AppData\Local\Temp\fxbundler762063117289376751\windows\bundle.wxi*525|C:\Users\Archie Cobbs\AppData\Local\Temp\fxbundler762063117289376751\windows\VeriPhase.wxs*30">
        <field>reg27C770ACE19E5E293FBC5389256D52D0</field>
        <field>0</field>
        <field>CLSID\{26764CDD-3998-4962-AC1D-D445A5969D20}\VersionIndependentProgID</field>
        <field/>
        <field>RDTiffDefinition.UserField</field>
        <field>RDTiffDefinition.dll</field>
      </row>
...
      <row sourceLineNumber="C:\Users\Archie Cobbs\AppData\Local\Temp\fxbundler762063117289376751\windows\RDTiffDefinition.dll.wxi*15|C:\Users\Archie Cobbs\AppData\Local\Temp\fxbundler762063117289376751\windows\bundle.wxi*525|C:\Users\Archie Cobbs\AppData\Local\Temp\fxbundler762063117289376751\windows\VeriPhase.wxs*30">
        <field>reg27C770ACE19E5E293FBC5389256D52D0</field>
        <field>0</field>
        <field>CLSID\{26764CDD-3998-4962-AC1D-D445A5969D20}\VersionIndependentProgID</field>
        <field/>
        <field>RDTiffDefinition.UserFields</field>
        <field>RDTiffDefinition.dll</field>
      </row>
...
```

Note the very subtle difference: the first entry says `<field>RDTiffDefinition.UserField</field>` while the second one says `<field>RDTiffDefinition.UserFields</field>` (note plural).

I'm guessing you're using some kind of hash function to generate the keys, but the hash function is stopping after 26 or fewer characters, so the distinction between `UserField` and `UserFields` is missed.

* Describe the behavior you expected and how it differed from the actual behavior.

Program crashes, but it is expected to work.

**Comment by archiecobbs** [comment] 2016-11-28 19:55
FYI, here is what `RDTiffDefinition.dll.wxs` looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
    <Fragment>
        <DirectoryRef Id="APPLICATIONFOLDER">
            <Component Win64="yes" Id="RDTiffDefinition.dll" Guid="{1B71D045-6762-4FDD-9B5E-B206B6D5F3E3}">
                <File ProcessorArchitecture="x64" Id="RDTiffDefinition.dll" KeyPath="yes" Source="RDTiffDefinition.dll">
                    <TypeLib Id="{453AACB0-3CF1-4673-8ECE-80D006F42181}" Description="Olympus NDT RDTiffDefinition 1.12 Type Library" HelpDirectory="APPLICATIONFOLDER" Language="0" MajorVersion="1" MinorVersion="12">
                        <Class Id="{1AE74EFF-CC02-4470-AAB5-74282F692890}" Context="InprocServer32" Description="Olympus NDT Channels Class" ThreadingModel="apartment" Programmable="yes">
                            <ProgId Id="RDTiffDefinition.Channels.3" Description="Olympus NDT Channels Class">
                                <ProgId Id="RDTiffDefinition.Channels" Description="Olympus NDT Channels Class" />
                            </ProgId>
                        </Class>
                        <Class Id="{26764CDD-3998-4962-AC1D-D445A5969D20}" Context="InprocServer32" Description="Olympus NDT UserField Class" ThreadingModel="apartment" Programmable="yes">
                            <ProgId Id="RDTiffDefinition.UserField.3" Description="Olympus NDT UserField Class">
                                <ProgId Id="RDTiffDefinition.UserField" Description="Olympus NDT UserField Class" />
                            </ProgId>
                            <ProgId Id="RDTiffDefinition.UserFields.3" Description="Olympus NDT UserFields Class">
                                <ProgId Id="RDTiffDefinition.UserFields" Description="Olympus NDT UserFields Class" />
                            </ProgId>
                        </Class>
                        <Class Id="{2DCEECAF-2969-423D-AA40-54AA8BEDF189}" Context="InprocServer32" Description="Olympus NDT Gate Class" ThreadingModel="apartment" Programmable="yes">
                            <ProgId Id="RDTiffDefinition.Gate.3" Description="Olympus NDT Gate Class">
                                <ProgId Id="RDTiffDefinition.Gate" Description="Olympus NDT Gate Class" />
                            </ProgId>
                        </Class>
                        <Class Id="{34D8C1B7-719E-453E-8A1F-5545E1BA7293}" Context="InprocServer32" Description="Olympus NDT DataAccess Class" ThreadingModel="apartment" Programmable="yes">
                            <ProgId Id="RDTiffDefinition.DataAccess.3" Description="Olympus NDT DataAccess Class">
                                <ProgId Id="RDTiffDefinition.DataAccess" Description="Olympus NDT DataAccess Class" />
                            </ProgId>
                        </Class>
                        ...
```

**Comment by rseanhall** [comment] 2016-12-06 17:44
Duplicate of #2858.

**Closed by rseanhall** 2016-12-06 17:44 UTC

**Comment by archiecobbs** [comment] 2016-12-06 17:49
Thanks for connecting to the existing issue.

But wow, this bug is over six years old...

(sad face)

**Comment by robmen** [comment] 2016-12-06 17:54
I'm kinda' surprised it isn't older. It's an original bug. 

The problem is that the fix is much harder than the workaround *and* the .wxs code you need to write when there is a fix isn't going to be very pretty.

All that makes it hard to get excited about fixing this particular bug when you look at all the other bugs available to be fixed.
