### ISSUE TITLE
Cannot load Heat.exe or one of its dependencies - VS 2022, 1.0.0.18

### ISSUE THREAD

**Issue by EQ-Aston** [wixtoolset/issues#6704] opened 2022-01-14 12:21 UTC
## Bugs

* Which version of WiX are you building with?
3.11.2

* Which version of Visual Studio are you building with (if any)?
Visual Studio 2022, 17.0.5

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
1.0.0.18

* Which version of .NET are you building with?
.NET Framework 4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
N/A

* Describe the problem and the steps to reproduce it.
When building Wix Installer project I am getting the following:
Could not load file or assembly 'file:///C:\My Root Folder\SolutionFolder\packages\Wix.3.11.2\build\..\tools\Heat.exe' or one of its dependencies. Visual Studio hangs for about 15 seconds then crashes.

This is the project entry that it was trying to 'Heat.exe' when the error occurred, this is also the first <heat> in the project file:
<HeatFile File="$(SolutionDir)InstallerFiles\TFS_BuildNumber.txt" PreprocessorVariable="var.TFSBuildNumberHarvestPath" OutputFile="$(ProjectDir)HarvestedFiles\TFSBuildNumber.wxs" ComponentGroupName="CGN_OFSERVER_TFS_BUILD_NUMBER" DirectoryRefId="DIR_INSTALLER_FILES" AutogenerateGuids="true" ToolPath="$(WixToolPath)" SuppressFragments="true" SuppressRegistry="true" SuppressRootDirectory="true" />

The 'My Root Folder' does have spaces in its name, I moved the folder to a new location without spaces in case that was the cause, it was still the same.

The Heat.exe is in the location specified.

This has only happens in Visual Studio 2022.
Visual studio 2019, 16.11.7, Wix extension 1.0.0.18 is working fine.

I am unable to provide the full error from the Output window as VS hangs I can't copy any information from it.

* Describe the behaviour you expected and how it differed from the actual behaviour.
I would expect the same behaviour in 2022 as in 2019, the project is compiled and the msi built.

**Comment by robmen** [comment] 2022-01-14 13:04
Almost certainly a duplicate of #6636.

If not, please add a link to a GitHub repo with your .sln and projects that reproduce the problem.

**Closed by robmen** 2022-01-14 13:04 UTC
Labels: triage

**Comment by EQ-Aston** [comment] 2022-01-14 14:13
#6636 did solve my problem, thank you.
