### ISSUE TITLE
Wix Installer Adding UI

### ISSUE THREAD

**Issue by elioYakidoo** [wixtoolset/issues#5280] opened 2016-04-27 20:11 UTC
Hello I am using the latest WixInstaller 4.0 for developing a service installer, and I am getting an error whenever I add a  UIRef to the the XML.
IE: 

`
<UIRef Id="WixUI_Mondo" />
    <UIRef Id="WixUI_ErrorProgressText" />
`

**The error I always get is the  "Error LGHT0001: '.' hexadecimal value 0x00, es not a valid character"**

Whenever I compile my code without this the msi file is generated with no issue, I have the references to the extension on my Visual Studio Project.

I am using VS2010
.Net Version 4.0
The error is whenever I build my WIX Project.
using Windows 8

**Comment by DevMichaelSabo** [comment] 2018-04-10 14:44
Have also error code with newest build 4
light.exe(0,0): error LGHT0001: '.', hexidezimaler Wert 0x00, ist ein ungültiges Zeichen.

**Comment by robmen** [comment] 2021-01-07 23:17
Duplicate of #4485

**Closed by robmen** 2021-01-07 23:17 UTC
Labels: FourOhPreviewZero, bug, linker
