### ISSUE TITLE
Wix Installer Update

### ISSUE THREAD

**Issue by vbjay** [wixtoolset/issues#5322] opened 2016-06-13 00:26 UTC
The wix installer checks for updates.  It finds them in the weekly builds.  There needs to be 2 tracks of updates.  Stable( released and approved by you) and weekly.  If I download a stable installer, it should not say it has an update and update to the latest weekly build.  If I download a weekly build installer, then tell me I have an updated installer.

**Comment by barnson** [comment] 2016-06-13 02:44
Dupe of https://github.com/wixtoolset/issues/issues/5292

**Closed by barnson** 2016-06-13 02:44 UTC
Labels: duplicate
