### ISSUE TITLE
Visual Studio hangs on saving new WiX project

### ISSUE THREAD

**Issue by vrapp** [wixtoolset/issues#5826] opened 2018-05-28 21:30 UTC
I installed WiX Toolset 3.11.1.2318 and WiX Toolset Visual Studio Extension 0.9.21.62588. In Visual Studio 2017 (v.15.7.2)  I create new project:

![p1](https://user-images.githubusercontent.com/2778779/40629875-9afabf3e-6293-11e8-8cb5-f6a66b061e7a.png)

after which I press "Save All" in Visual studio without any modifications. I make selections in "Save Project" dialog, press "Save", at which point Visual Studio hangs. It does not hang with other types of projects. including the same-named one from under WiX node under WiX Toolset.

**Comment by barnson** [comment] 2018-05-28 21:35
Duplicate of https://github.com/wixtoolset/issues/issues/3218.

**Closed by barnson** 2018-05-28 21:35 UTC
Labels: duplicate
