### ISSUE TITLE
[Supporting the platform] Content of the 'Setup' pop-up is not visible properly when the screen is resized up to 400%

### ISSUE THREAD

**Issue by tgugler** [wixtoolset/issues#6363] opened 2021-02-19 16:35 UTC
If this issue is a bug:

* Which version of WiX are you building with?

> 3.14.0.1119

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2017

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.4

* Which version of .NET are you building with?

> Not applicable

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Not applicable

* Describe the problem and the steps to reproduce it.

User Experience: 
If the content of the pop-up is not visible properly at 400% resize, the AT user will not able to access the content. The user will face difficulty while navigating through the screen.

Note: User credentials should NOT be included in the bug.

Pre-requisite:
Resize the screen up to 400%.

Repro Steps:
1. Launch the "NPS Extension For Azure MFA" setup file.
2. Navigate to "MICROSOFT SOFTWARE LICENSE TERMS" popup window and select "Install" button.​
3. After successful installation of Setup, again install the same setup.​
4. Navigate to "Modify Setup" popup window and select "Uninstall" button.​
5. Navigate all the controls of "Setup Progress/Setup Successful" popup window.
6. Verify the issue.

Actual Result:
Content of the 'Setup' pop-up is not visible properly when the screen is resized up to 400%.

Expected Result:
Content of the 'Setup' pop-up should be visible properly when the screen is resized up to 400%.

Note:
This issue exists throughout the application.

![MAS1 4 10_screen not visible properly at 400 resize](https://user-images.githubusercontent.com/12263599/108533127-7becbe00-728d-11eb-8796-a830c9734c33.png)

**Comment by rseanhall** [comment] 2021-02-19 16:41
@tgugler This is a duplicate of https://github.com/wixtoolset/issues/issues/6241. As we commented there, we need more information about this issue. And in general, the issues you are creating are not written for the right audience. We need more context about these issues, you can't just put some text in from your test case.

**Closed** 2021-03-04 17:46 UTC
Labels: duplicate
