### ISSUE TITLE
Unable to install Votive2022.vsix within Visual Studio Pro 2022 17.2.5 

### ISSUE THREAD

**Issue by ixigrec** [wixtoolset/issues#6826] opened 2022-07-08 13:14 UTC
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> Wix 3.11.2

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Professional 2022

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Votive2022.vsix 1.0.0.20

* Which version of .NET are you building with?

> .NET Framework 4.8

* Describe the problem and the steps to reproduce it.

> For information, my environment is disconnected from Internet.
> When I tried to install the Wix Visual Studio Extension (Votive2022.vsix) it always fails. I join the install log if can help (in french only, sorry :/).
> [Votive2022_VsPro2022-17.2.5_InstallFail.log](https://github.com/wixtoolset/issues/files/9072294/Votive2022_VsPro2022-17.2.5_InstallFail.log)
* Describe the behavior you expected and how it differed from the actual behavior.

> The Wix Visual Studio 2022 extension is installed in my Visual Studio Professional 2022.

thanks,

**Comment by barnson** [comment] 2022-07-08 13:30
Fixed in VS 17.2.5. https://github.com/wixtoolset/issues/issues/6803

**Closed by barnson** 2022-07-08 13:30 UTC
Labels: triage

**Comment by ixigrec** [comment] 2022-07-08 13:34
Hi @barnson,

For info I tried to install this extension to VS 2022 Professional 17.2.5 
![image](https://user-images.githubusercontent.com/1623688/178002088-29472935-6811-4674-8f15-58fae350447f.png)

I update my VS to 17.2.5 after reading #6803

**Comment by rseanhall** [comment] 2022-07-08 15:30
It would have been more correct to close this by pointing to https://github.com/wixtoolset/issues/issues/6786

**Comment by robmen** [comment] 2022-07-08 15:57
Said kindlier, the error in the log file suggests this is a duplicate of #6786.

    08/07/2022 14:58:01 - Détails de la signature...
    08/07/2022 14:58:01 - 	Extension is signed with an invalid timestamp.

@ixigrec my last hypothesis from #6786 is that the VSIX Installer has issues validating timestamps in some (non-US?) locales. Unfortunately, the issue is in the VSIX Installer and needs to be tracked against the Visual Studio team https://developercommunity.visualstudio.com/home since we can't fix it (and I haven't reproduced the issue).

The hope was that VS would address all the issues in 17.2.5 when this was fixed https://developercommunity.visualstudio.com/t/Installation-of-wixtoolset-extension-cor/10057006 but it seems this one remains.
