### ISSUE TITLE
WiX 4.0 Light.exe ArgumentException InvalidXmlChar 0x00 when writing wixpdb

### ISSUE THREAD

**Issue by JurekM** [wixtoolset/issues#5169] opened 2016-01-02 20:20 UTC
WiX 3.8 worked fine. WiX 4.0 throws. Using "-spdb" works around the problem. Only happens for two out of seven WiX projects in a solution. Only these two use Heat.exe. All projects share some files. There is no embedded binary zero in any of the source files including wixproj and Heat.exe output files. 100% repro both Debug and Release.
# 

C:\Projects\MyStuff\Server\WiX_MyAppSetup>"C:\Program Files (x86)\WiX Toolset v4.0\bin\Light.exe" -out obj\Release\MyAppSetup.msi -pdbout C:\Projects\MyStuff\Server\WiX_MyAppSetup\obj\Release\MyAppSetup.wixpdb -cultures:null -ext "C:\Program Files (x86)\WiX Toolset v4.0\bin\WixUIExtension.dll" -contentsfile obj\Release\WiX_MyAppSetup.wixproj.BindContentsFileList.txt -outputsfile obj\Release\WiX_MyAppSetup.wixproj.BindOutputsFileList.txt -builtoutputsfile obj\Release\WiX_MyAppSetup.wixproj.BindBuiltOutputsFileList.txt -wixprojectfile C:\Projects\MyStuff\Server\WiX_MyAppSetup\WiX_MyAppSetup.wixproj obj\Release\AdcoDlls.wixobj obj\Release\AdcoFiles.wixobj obj\Release\MyAppSetup.wixobj
WiX Toolset Linker version 4.0.3430.0
Copyright (c) Outercurve Foundation. All rights reserved.

Opening database at: C:\Users\jurekm\AppData\Local\Temp\2\wix160102T1515453760\MyAppSetup.msi
light.exe : error LGHT0001 : '.', hexadecimal value 0x00, is an invalid character.

Exception Type: System.ArgumentException

Stack Trace:
   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte\* pDst, Boolean entitize)
   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char\* pSrc, Char\* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at WixToolset.Data.Field.Write(XmlWriter writer)
   at WixToolset.Data.Row.Write(XmlWriter writer)
   at WixToolset.Data.Table.Write(XmlWriter writer)
   at WixToolset.Data.Output.Write(XmlWriter writer)
   at WixToolset.Data.Pdb.Write(XmlWriter writer)
   at WixToolset.Data.Pdb.Save(String path)
   at WixToolset.Bind.BindDatabaseCommand.Execute()
   at WixToolset.Binder.BindDatabase(Output output, String databaseFile, IEnumerable`1& fileTransfers, IEnumerable`1& contentPaths)
   at WixToolset.Binder.Bind(Output output, String file)
   at WixToolset.Tools.Light.Run()
   at WixToolset.Tools.Light.Execute(String[] args)

**Comment by fourpastmidnight** [comment] 2016-03-06 20:50
I am also getting this same error from `light.exe` trying to create a MSI installer for GitForWindows, but to my knowledge, no RTF file is involved. Using the `-v` option, I got the following output from the Visual Studio Build Output window, which seems to indicate something with one of the XML files:

```text
WiX Toolset Linker version 4.0.3729.0
	Copyright (c) Outercurve Foundation. All rights reserved.
	Updating file information.
	Creating cabinet files.
	There will be '8' threads used to produce CAB files.
	Creating cabinet 'C:\Users\<MyUserDir>\AppData\Local\Temp\wix160306T1436087678\#git1.cab'.
	Creating cabinet 'C:\Users\<MyUserDir>\AppData\Local\Temp\wix160306T1436087678\#git2.cab'.
	Generating database.
	Binder temporary directory located at 'C:\Users\<MyUserDir>\AppData\Local\Temp\wix160306T1436087678'.
light.exe(0,0): error LGHT0001: '.', hexadecimal value 0x00, is an invalid character.
	Exception Type: System.ArgumentException
	Stack Trace:
	   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize)
	   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
	   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
	   at System.Xml.XmlWellFormedWriter.WriteString(String text)
	   at WixToolset.Data.Field.Write(XmlWriter writer)
	   at WixToolset.Data.Row.Write(XmlWriter writer)
	   at WixToolset.Data.Table.Write(XmlWriter writer)
	   at WixToolset.Data.Output.Write(XmlWriter writer)
	   at WixToolset.Data.Pdb.Write(XmlWriter writer)
	   at WixToolset.Data.Pdb.Save(String path)
	   at WixToolset.Bind.BindDatabaseCommand.Execute()
	   at WixToolset.Binder.BindDatabase(Output output, String databaseFile, IEnumerable`1& fileTransfers, IEnumerable`1& contentPaths)
	   at WixToolset.Binder.Bind(Output output, String file)
	   at WixToolset.Tools.Light.Run()
	   at WixToolset.Tools.Light.Execute(String[] args)
Done building project "GitForWindows-MSI.wixproj" -- FAILED.
```

I can confirm that using `-spdb` does work around this issue.

**Comment by fourpastmidnight** [comment] 2016-05-16 00:53
So, today I was working through my commit history over on Git for Windows for the MSI I'm working on over there. @robmen asked me to not use the `-spdb` switch -- and I agree that that switch shouldn't be included on the command line because the PDB can aid debugging. So, I thought I'd try and nail down when the error above began occurring. I think I may have something.

I reordered my commit history, and for the longest time, the MSI I've been working on has no UI. The MSI would build just fine with no problems while outputting a PDB. During initial development of the UI, I fashioned my own UI from scratch to begin (mostly because I've been out of practice!!). Again, I had no problems building the MSI and outputting a PDB.

BUT, when I decided to use some of the standard WiX UI dialogs, that means that I needed to include a reference to `WixUIExtension.dll`. Once I started linking with that extension, this error occurred, and I am forced to link with the `-spdb` switch to work around it.

So it appears that the source of the error resides in the `WixUIExtension.dll` library. Hope that helps.

**Comment by fourpastmidnight** [comment] 2017-01-26 20:36
Today, I was looking at the Release Notes for Particular Software's latest release of ServiceInsights and they fixed a bug very similar to what's being experienced here, `'.', hexadecimal value 0x00, is an invalid character.`

Here's a link to the [issue](https://github.com/Particular/ServiceInsight/issues/501) and the [commit](https://github.com/Particular/ServiceInsight/commit/35982a1d24f9edbaf0028a0b1c27e386bf3cbd39) that fixed it. If I'm reading the changes in the commit correctly, this appears to be an issue with the .NET XML Parser not correctly parsing the XML document if the XML document does not include the UTF-8 BOM.

Hopefully this is enough information to finally resolve this issue with the WiX Toolset.

**Comment by JurekM** [comment] 2017-01-29 21:08
Searching for this message reveals that binary zero at the end of data is quite common.

**Comment by robmen** [comment] 2020-07-22 22:12
This is a duplicate of https://github.com/wixtoolset/issues/issues/4485

**Closed by robmen** 2020-07-22 22:12 UTC
Labels: duplicate
