### ISSUE TITLE
When launching Burn eleveted with \" agruments multiple duplicate burn processes are created.

### ISSUE THREAD

**Issue by QaiserSadiq** [wixtoolset/issues#5215] opened 2016-02-17 23:12 UTC
If you launch Burn elevated and pass in a path that ends with \", multiple duplicate processes get created on the machine and this continues until the system's memory gets used up.  

This can be easily repro'd with the vcredist.exe (which uses the Wix Generic Bootrapper).  I launched it from a elevated command prompt and passed in a path ended with \", no UI appeared and in my task manager I noticed multiple vcredist processes getting created.

**Comment by robmen** [comment] 2016-02-18 00:34
I cannot reproduce this issue with WiX v3.10.2. Can upgrade and if it still reproduces provide the exact command-line you are using? A log file would be good as well.

**Comment by rseanhall** [comment] 2016-02-18 00:55
This should be a duplicate of #3890

**Comment by robmen** [comment] 2016-02-18 04:30
Thanks @rseanhall I thought this sounded familiar.

**Closed by robmen** 2016-02-18 04:30 UTC
Labels: duplicate
