### ISSUE TITLE
Condition that spans multiple lines does not convert correctly to WiX v4

### ISSUE THREAD

**Issue by dbengle** [wixtoolset/issues#7739] opened 2023-09-20 20:50 UTC
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

WiX 4.0.2

* Which version of Visual Studio are you building with (if any)?
Visual Studio 2022 17.7.4  

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

Heat Wave for VS2022

* Which version of .NET are you building with?

4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

n/a

* Describe the problem and the steps to reproduce it.

Create a WiX v3 package with a <Condition> with text that spans multiple lines, such as this:

            <Feature Id="ShellExtensionFeature" Level="0" InstallDefault="local" >

                 <Condition Level="1">
                     (NOT Installed AND NOT PERUSER) OR
                     (Installed AND ZOS_SHELL_EXTENSION_INSTALLED)
                 </Condition>

                <ComponentGroupRef Id="ShellExtComponents" />

            </Feature>

Then convert the package to WiX v4.

* Describe the behavior you expected and how it differed from the actual behavior.

The <Condition> will convert to this in WiX v4 (the &#xA; causes syntax errors when you build the package):

            <Feature Id="ShellExtensionFeature" Level="0" InstallDefault="local">

                 <Level Value="1" Condition="(NOT Installed AND NOT PERUSER) OR&#xA;    (Installed AND ZOS_SHELL_EXTENSION_INSTALLED)" />

                <ComponentGroupRef Id="ShellExtComponents" />

            </Feature>

**Comment by cpuwzd** [comment] 2023-10-08 03:08
Okay @robmen and @barnson, I committed to this issue, but you haven't assigned it to me. Remind me, so I get it right on my first try: Once it is assigned, do I push my feature branch to wixtoolset/develop and generate a pull request. That doesn't quite sound right. Just make it easy. The pull request is ready for review, if not integration. Looks good to me. The problem is more general than reported. The hardest work was generating all the new test cases.

Ron

**Comment by robmen** [comment] 2023-10-08 06:36
Thanks. GItHub won't allow us to assign an issue to you until you comment on it.

I recommend pushing to a branch on your fork of `wixtoolset/wix` then send the pull request from there targeting `develop`.

**Closed** 2023-12-12 14:49 UTC
Labels: wixcop
