### ISSUE TITLE
v4 docs missing Condition Attribute on Custom element

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#7062] opened 2022-12-05 03:43 UTC
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

v4 preview

* Which version of Visual Studio are you building with (if any)?

2022 17.4.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

Heatwave 0.9.0.5

* Describe the problem and the steps to reproduce it.

When I try to sequence a custom action, intellisense says the 'Condition' attribute is not defined.  The build success and the condition is present in the sequence table.  I see this in InstallUISequence and InstallExecuteSequence and assume it applies to the others also.  Also as expected it's not listed here  https://wixtoolset.org/docs/reference/schema/wxs/custom/ either.

* Describe the behavior you expected and how it differed from the actual behavior.

Schema docs to have this attribute. Intellisense so I don't have to guess.

**Comment by robmen** [comment] 2022-12-05 18:03
The WiX XSDs are in the `web` repo now, as they are used to as the source for the reference documentation. See https://github.com/wixtoolset/web/tree/master/src/xsd4

**Comment by chrpai** [comment] 2022-12-05 18:39
I thought I looked there. I'm willing to take this one if you'd like.  If it's faster for Rob to just do it that's fine too.

**Comment by chrpai** [comment] 2022-12-05 18:49
I looked through the old v3 schema and couldn't find any verbiage for the innertext condition.  I probably can't wordsmith this the way you would so best I don't take it.

 <xs:attribute name="Condition" type="xs:string">
        <xs:annotation>
          <xs:documentation>Condition to determine whether to execute the Custom Action. If this evaluates to false, the MSI Custom Action is not executed.</xs:documentation>
        </xs:annotation>
      </xs:attribute>

**Comment by robmen** [comment] 2022-12-05 23:16
Duplicate of #7029

**Closed by robmen** 2022-12-05 23:16 UTC
Labels: documentation
