### ISSUE TITLE
Wix 3.10.1 - Burn: Adding a big payload to a bundle crashes light

### ISSUE THREAD

**Issue by dsed** [wixtoolset/issues#5205] opened 2016-02-09 06:59 UTC
When trying to add a somewhat bigger msi (2,56 GB (2.752.888.832 Bytes)) to a bundle using MsiPackage light crashes with the following message:
light.exe : error LGHT0001: Arithmetic operation resulted in an overflow. [XXX]

  Exception Type: System.OverflowException

  Stack Trace:
     at Microsoft.Tools.WindowsInstallerXml.PayloadInfoRow.ResolvePayloadInfo(IPayloadInfo payloadInfo)
     at Microsoft.Tools.WindowsInstallerXml.PayloadInfoRow.FillFromPayloadRow(Output output, Row payloadRow)
     at Microsoft.Tools.WindowsInstallerXml.Binder.BindBundle(Output bundle, String bundleFile)
     at Microsoft.Tools.WindowsInstallerXml.Binder.Bind(Output output, String file)
     at Microsoft.Tools.WindowsInstallerXml.Tools.Light.Run(String[] args)

I am aware of that there is a imposed limit, but I am expecting it to be around 4 GB, here it seems to be around 2 GB.

**Comment by barnson** [comment] 2016-02-09 21:17
It shouldn't crash but the limit is 2GB.

**Comment by rseanhall** [comment] 2020-12-14 02:45
Duplicate of https://github.com/wixtoolset/issues/issues/4008

**Closed by rseanhall** 2020-12-14 02:45 UTC
Labels: bug, burn, light
