### ISSUE TITLE
Page Not Found: /schemas/v4/wxs/util

### ISSUE THREAD

**Issue by AngelinaK31** [wixtoolset/issues#7566] opened 2023-06-20 20:36 UTC
### WiX Toolset Page URL

https://wixtoolset.org/schemas/v4/wxs/util

**Comment by barnson** [comment] 2023-06-20 20:44
Dupe of https://github.com/wixtoolset/issues/issues/7561. Schema docs are available at https://wixtoolset.org/docs/schema/.

**Closed by barnson** 2023-06-20 20:44 UTC
Labels: duplicate
