### ISSUE TITLE
Page Not Found: /docs/docs/v3/

### ISSUE THREAD

**Issue by donutboyy** [wixtoolset/issues#7008] opened 2022-11-14 07:33 UTC
### WiX Toolset Page URL

https://wixtoolset.org/docs/docs/v3/

### Page URL that linked to WiX Toolset

https://wixtoolset.org/docs/wix3/

### Additional information (optional)

😱 typo, should just be `https://wixtoolset.org/docs/v3/`

**Comment by robmen** [comment] 2022-11-14 07:40
Duplicate of #7006

**Closed by robmen** 2022-11-14 07:40 UTC
Labels: triage
