### ISSUE TITLE
Not able to customize the built-in Wix UI dialogue text from "Computing space requirements" to "Computing space requirements. Please Wait."

### ISSUE THREAD

**Issue by sanjeevs-optimus** [wixtoolset/issues#5897] opened 2018-11-06 05:55 UTC
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> (3.11)

* Which version of Visual Studio are you building with (if any)?

> (VS 13)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (Visual Studio 2013 Extension)

* Which version of .NET are you building with?

> (4.5)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (All Windows Versions(7,8,10))

* Describe the problem and the steps to reproduce it.

> I have overrriden the following string values present of the "WixUI_en-us.wxl" file in "MyCustom.wxl" file:-

From (WixUI_en-us.wxl):
   ```
    <String Id="ProgressTextFileCost" Overridable="yes">Computing space requirements</String>
    <String Id="ProgressTextCostInitialize" Overridable="yes">Computing space requirements</String>
    <String Id="ProgressTextCostFinalize" Overridable="yes">Computing space requirements</String>
```
To (MyCustom.wxl):
   ```
    <String Id="ProgressTextFileCost">Computing space requirements. Please Wait.</String>
    <String Id="ProgressTextCostInitialize">Computing space requirements. Please Wait.</String>
    <String Id="ProgressTextCostFinalize">Computing space requirements. Please Wait.</String>
```

But these values are not reflecting and hence we are not able to see these override values in the Wix UI dialogue.

* Describe the behaviour you expected and how it differed from the actual behaviour.

> These values must be reflected in the Wix UI dialogue after overriding the built-in string values in the "MyCustom.wxl" file but these values are not reflecting.

**Comment by barnson** [comment] 2018-11-06 14:39
Duplicate of https://github.com/wixtoolset/issues/issues/5786.

**Closed by barnson** 2018-11-06 14:39 UTC
Labels: duplicate
