### ISSUE TITLE
New Project in Visual Studio - duplicate entries

### ISSUE THREAD

**Issue by vrapp** [wixtoolset/issues#5825] opened 2018-05-28 21:20 UTC
I installed Wix Toolset 3.11.1.2318, which in the end asked if I also need WiX for Visual Studio; so I also installed WiX Toolset Visual Studio Extension 0.9.21.62588. When I try to create new project in Visual Studio 2017 (v.15.7.2), this is what I see as the choices:

![p1](https://user-images.githubusercontent.com/2778779/40629655-84f072fc-6292-11e8-9869-a39dea1318ab.png)

It looks like duplicate of the same.

**Comment by barnson** [comment] 2018-05-28 21:35
Duplicate of https://github.com/wixtoolset/issues/issues/5531.

**Closed by barnson** 2018-05-28 21:35 UTC
Labels: duplicate
