### ISSUE TITLE
Custom action VS2017Setup does not detect VS2017 when VS2019 is also installed

### ISSUE THREAD

**Issue by XomegaNet** [wixtoolset/issues#5979] opened 2019-04-07 22:34 UTC
When you have both VS2017 and VS2019 installed side by side, the custom action `VS2017Setup` in Wix Toolset **v3.110.1701** does not detect the VS2017 instance, which makes it impossible to install our extension [Xomega.Net for Visual Studio 2017](https://xomega.net).

It works fine when only VS2017 is installed. Here are the MSI logs for `VSFindInstances` action when only VS2017 installed.

```
MSI (c) (E8:2C) [16:38:06:613]: Doing action: VSFindInstances
MSI (c) (E8:2C) [16:38:06:613]: Note: 1: 2205 2:  3: ActionText 
Action 16:38:06: VSFindInstances. 
Action start 16:38:06: VSFindInstances.
MSI (c) (E8:80) [16:38:06:617]: Invoking remote custom action. DLL: C:\Users\Admin\AppData\Local\Temp\MSI2840.tmp, Entrypoint: FindInstances
MSI (c) (E8:70) [16:38:06:619]: Cloaking enabled.
MSI (c) (E8:70) [16:38:06:619]: Attempting to enable all disabled privileges before calling Install on Server
MSI (c) (E8:70) [16:38:06:619]: Connected to service for CA interface.
MSI (c) (E8!D4) [16:38:06:722]: PROPERTY CHANGE: Adding VS2017_ROOT_FOLDER property. Its value is 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise'.
MSI (c) (E8!D4) [16:38:06:724]: PROPERTY CHANGE: Adding VS2017_IDE_VWD_PROJECTSYSTEM_INSTALLED property. Its value is '1'.
MSI (c) (E8!D4) [16:38:06:725]: PROPERTY CHANGE: Adding VS2017_IDE_FSHARP_PROJECTSYSTEM_INSTALLED property. Its value is '1'.
MSI (c) (E8!D4) [16:38:06:725]: PROPERTY CHANGE: Adding VS2017_IDE_MODELING_PROJECTSYSTEM_INSTALLED property. Its value is '1'.
MSI (c) (E8!D4) [16:38:06:725]: PROPERTY CHANGE: Adding VS2017_IDE_VB_PROJECTSYSTEM_INSTALLED property. Its value is '1'.
MSI (c) (E8!D4) [16:38:06:725]: PROPERTY CHANGE: Adding VS2017_IDE_VCSHARP_PROJECTSYSTEM_INSTALLED property. Its value is '1'.
Action ended 16:38:06: VSFindInstances. Return value 1.
```

And the following logs are for the same action when both VS2017 and VS2019 are installed.

```
MSI (c) (F8:D8) [21:08:44:767]: Doing action: VSFindInstances
MSI (c) (F8:D8) [21:08:44:767]: Note: 1: 2205 2:  3: ActionText 
Action 21:08:44: VSFindInstances. 
Action start 21:08:44: VSFindInstances.
MSI (c) (F8:F4) [21:08:44:771]: Invoking remote custom action. DLL: C:\Users\Admin\AppData\Local\Temp\MSIEE8D.tmp, Entrypoint: FindInstances
MSI (c) (F8:D0) [21:08:44:773]: Cloaking enabled.
MSI (c) (F8:D0) [21:08:44:773]: Attempting to enable all disabled privileges before calling Install on Server
MSI (c) (F8:D0) [21:08:44:773]: Connected to service for CA interface.
Action ended 21:08:44: VSFindInstances. Return value 1.
```

As you can see, it does not set the VS2017_xxx properties, as if no VS2017 is installed.

Please advise on why this is happening, and what can we do to fix it.

**Comment by XomegaNet** [comment] 2019-04-10 00:52
@chrpai thank you for your support and for the references to your workaround. We tried your custom action to help detect VS2017, and it worked fine.

A user of our extension, who had this issue, also reported that the original installation somehow worked for him with both 2017 and 2019 side by side after rebuilding his machine from ground up. But we were still able to observe this issue in our testing environment, and verified that your custom action fixes it.

While not as critical for us now, I think this issue should be still looked at and fixed in the WiX Toolset for the rest of the users.

**Comment by chrpai** [comment] 2019-04-10 01:12
How are your C++ chops?  I learned ANSI C on Solaris back in the 90s but never learned C++ on Windows.  Your more then welcome to look through the source code (primarily https://github.com/wixtoolset/wix3/blob/develop/src/ext/VSExtension/ca/vsca.cpp )   and try to identify the root cause and submit a pull request.  I would if I had the C++ chops.

**Comment by XomegaNet** [comment] 2019-04-10 03:16
I was looking through that file, but could spot any smoking gun without having to debug it. I did notice though, that it was using the old `ISetupConfiguration.EnumInstances` method, while your custom action uses the newer `ISetupConfiguration2.EnumAllInstances` method.

I cannot quite tell the difference from the [documentation of those methods](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.setup.configuration.isetupconfiguration2?view=visualstudiosdk-2017), so it probably requires debugging that C++ code. Alternatively, that implementation can be replaced with your custom action in the WiX Toolset, but I don't know what side effects this may have.

**Comment by chrpai** [comment] 2019-04-10 10:44
While I have no concerns doing so, the WiX team isn't going to take a dependency on the CLR in a CA.

**Comment by chrpai** [comment] 2019-04-10 13:18
@XomegaNet  I have a private fork and CI/BUILD of WiX3 with the V4 changes ported into it.  Please email me at chrpai@iswix.com if you'd like to collaborate offline on this.

**Comment by barnson** [comment] 2019-04-11 16:37
@heaths, any ideas?

**Comment by heaths** [comment] 2019-04-12 00:08
The query API doesn't need to be updated, but new properties would need to be added for VS2019. As for why the properties weren't defined when VS2019 was installed, nothing comes to mind off hand. But defining new version-specific properties has always been the way. Maybe to avoid adding support we should use a deterministic generation algorithm. Too late for 3.14? But would it be too late for adding 2019 properties to 3.14? I could look into it and why the VS2017 properties weren't defined in that case (guessing it has something to do with the "latest" detection).

**Comment by barnson** [comment] 2019-04-12 00:10
Yeah, really two issues:

1. Bug: VS2017 isn't detected when SxS with VS2019.
2. Feature: VS2019 should be detected as distinct from VS2017.

**Comment by heaths** [comment] 2019-04-12 00:21
Reviewing the code, I'm not sure why VS2017 properties wouldn't be defined. @XomegaNet, can you run the following and post the results?

```
"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -products *
```

Please also include the header.

**Comment by XomegaNet** [comment] 2019-04-12 01:41
@heaths, [here](https://github.com/wixtoolset/issues/files/3071232/vswhere.txt) are the results from that command, which I ran on the machine with this issue.

Please let me know if you need any additional information or any further help in troubleshooting this issue.

**Comment by barnson** [comment] 2019-04-25 16:32
@heaths: Triage team says hello and pokes in your general direction for an update.

**Comment by heaths** [comment] 2019-04-25 20:25
Sorry, I didn't see that he had replied (perhaps opened the notification in a new tab and closed it accidentally). Both instances are complete and, therefore, launchable. The original possibility I was considering was that an instance wasn't launchable. `ISetupConfiguration::EnumInstances()` only enumerates launchable instances. Looking through the existing wix3 code and even the changes @chrpai made following the same pattern I established for VS2017 (intentionally trying to make it a copy/paste sort of change), nothing stands out as to why. It's possible that at the time @XomegaNet ran this, the VS2017 instance was in need of a reboot (which makes VS not launchable, since it would otherwise be in a torn, inconsistent state - something we also tried to prevent when we used burn).

@XomegaNet, with your original MSI that had the issue, does the problem still repro?

**Comment by chrpai** [comment] 2019-04-25 20:52
@heaths  FWIW I was building with a private 3.14 that had my change and I had seen it working on 2017 and 2019.  Then one day I saw it fail to detect a 2019.  I then went back to using 3.11 and rolled my own DTF custom action which I have yet to see fail.   I developed this in a clean room based on various web searches (which probably had your name on them)   and @XomegaNet  noticed that I was using a different interface / method.  Code is below.

https://github.com/iswix-llc/iswix/blob/wpf-dev/Installer/IsWiXActions/CustomAction.cs

Sorry for the copy/paste attempt to extend your pattern.  I haven't coded C in literally two decades.

**Comment by heaths** [comment] 2019-04-25 21:18
The managed interface is an RCW for the native APIs the native CAs are using (I wrote them both). By default, the API I mentioned above only finds *launchable* instances. If you recently took an update and, for example, didn't restart, the instance wouldn't be enumerated. There no reason the managed would work when the native doesn't, which is why I'm wondering if @XomegaNet can still repro this - that maybe his 2017 instance at that point in time required a reboot or had other vital errors (requires repair).

**Comment by chrpai** [comment] 2019-04-26 13:29
@heaths  I'm not sure you looked at my source code and noticed that:

WiX VSEXT CA is using SetupConfiguration EnumInstances  
IsWiX DTF CA is using  ISetupConfiguration2 EnumAllInstances (iswix-dtf-ca).

As I'm sure you know, according to MSDN the former "Enumerates all launchable product instances installed" and the later "Gets the instance for the current process path"

I'm wondering if could be the difference as to why I'm not having any issues.

 https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.setup.configuration.isetupconfiguration2?view=visualstudiosdk-2017

**Comment by heaths** [comment] 2019-04-26 14:23
If the instance isn't launchable, it's in an unsupported state. Calling `EnumInstances` was intentional. Your VS MEF cache could get hosed, for example, requiring a repair anyway, which is costly. Best case scenario, people need a reboot. And it shouldn't be up to the installer dev to decide: it negatively impacts the end user. VSIXInstaller didn't block on this condition before and problem did occur. Those problems have been almost eliminated by more careful state management between setup and VS.

Perhaps I could use that API and at least log when a "broken" instance is enumerated and why it was skipped.

**Comment by chrpai** [comment] 2019-04-26 14:53
Perhaps set a property to use with a launch condition to block when a problem with vs is detected.

Just filtering the instance makes it seem like there is a problem with the product msi that is trying to register with visual studio.


On Apr 26, 2019, at 9:23 AM, Heath Stewart <notifications@github.com<mailto:notifications@github.com>> wrote:


If the instance isn't launchable, it's in an unsupported state. Calling EnumInstances was intentional. Your VS MEF cache could get hosed, for example, requiring a repair anyway, which is costly. Best case scenario, people need a reboot. And it shouldn't be up to the installer dev to decide: it negatively impacts the end user. VSIXInstaller didn't block on this condition before and problem did occur. Those problems have been almost eliminated by more careful state management between setup and VS.

Perhaps I could use that API and at least log when a "broken" instance is enumerated and why it was skipped.

**Comment by heaths** [comment] 2019-04-26 20:46
That leaves it up to the setup dev which, if ignored, negatively impacts the end user.

**Comment by XomegaNet** [comment] 2019-04-26 21:39
Sorry for being silent, as I just got back from vacation. Our test machine had both instances (2017 and 2019) freshly installed one after another, and launchable with no issues. I'm not sure if the `vswhere` lists all instances or just launchable ones, but they were both listed there. I can still reproduce the issue with the original msi on our test machine.

As I have already mentioned, a user of our extension, who had this issue on his machine, also reported that the original installation somehow worked for him with both 2017 and 2019 side by side after rebuilding his machine from ground up. So there must be some weird bug somewhere, but I just don't know how to figure it out.

@heaths, if there is any sample VS project that I can run and debug on my test machine, then I can step through the code and pinpoint the exact issue. I tried creating a sample VC++ project from the checked in vsca.cpp code, but was not successful so far, so any help would be appreciated.

**Comment by heaths** [comment] 2019-04-26 22:15
vswhere.exe uses the same installed query API as the custom actions. The only thing that needs debugging is the custom actions, so if you're willing and since you have a repro machine, building debug versions of those binaries and stepping through the CA would be most helpful.

**Comment by XomegaNet** [comment] 2019-04-30 03:51
Ok @heaths, I was finally able to debug the CA code in the [vsca.cpp](https://github.com/wixtoolset/wix3/blob/develop/src/ext/VSExtension/ca/vsca.cpp) on our test machine, and here is what happens.

The `pEnumInstances` returned from the `pConfiguration->EnumInstances(&pEnumInstances)` call enumerates VS 2017 first and then the 2019 version. As a result the `qwVersion` is assigned to the VS2019 version by the time it finishes the `do/while` loop, and the subsequent [call to process the VS2017 version](https://github.com/wixtoolset/wix3/blob/7981ccf4ae00f1a42f3f82854a4e1608d1845752/src/ext/VSExtension/ca/vsca.cpp#L155) (which adds the properties) never gets invoked, since it [fails the corresponding condition](https://github.com/wixtoolset/wix3/blob/7981ccf4ae00f1a42f3f82854a4e1608d1845752/src/ext/VSExtension/ca/vsca.cpp#L153) check for the `qwVersion`.

If `EnumInstances` happens to enumerate versions in the order they were originally installed on the machine, and our user installed VS2017 after installing VS2019 when he rebuilt his machine from the ground up, then I can see how this would've worked for him, since the VS2017 version would be the last one in that list.

**Comment by heaths** [comment] 2019-04-30 05:33
Thanks for debugging into this. The order enumerated is non-deterministic. Instances - whether the same or different versions - can be installed in any order. Based on your findings and reviewing the code, I see the problem. We should reset `qwVersion` in the do/while loop (though not strictly necessary), but also keep track of which processing functions we called and call all of those again with a `NULL` instance to set the properties to the latest version of each major version.

@barnson should this go only into wix4 or also wix3? Still time for 3.14, right?

**Comment by chrpai** [comment] 2019-04-30 13:32
That's excellent news.  I can do the testing if we get a build to look at.  If I understand correctly I need to have snapshots where  2017 was installed first and when 2019 was installed first.

I hope we can get this in 3.14 and word out to developers that they need to upgrade and rebuild  to flush this bug out of their installers in prod.

**Comment by barnson** [comment] 2019-04-30 14:16
Yeah, we'd take this in v3.14, @heaths.

**Comment by heaths** [comment] 2019-05-05 17:37
@barnson the corresponding wix3 change is still pending, so you might want to reopen this issue.

**Closed** 2019-05-09 20:02 UTC

**Comment by nekobul** [comment] 2019-05-16 01:25
Is there a built available for download with this latest fix?

**Comment by nekobul** [comment] 2019-05-21 01:47
Five days and still no response. Is anybody reading these posts?

**Comment by BMurri** [comment] 2019-05-21 02:49
That would be a v3.14 build, and there hasn't been one of those dropped in some time. I would assume closer to the release of v4...

**Comment by robmen** [comment] 2019-05-21 02:50
1. We triage all untriaged issues every other week.
2. You're commenting on a closed issue. The wix-users mailing list is where we discuss things.

**Comment by nekobul** [comment] 2019-05-21 11:39
Rob,

I have asked a follow-up question on the mailing list that you have not responded. That's why I have decided to ask here. It is clear WiX is way behind with the support for VS 2019 and I would recommend you move this on top of your priorities. We need a new built NOW which includes all the latest fixes related to VS 2019. Thank you for your understanding!
