### ISSUE TITLE
Unable to change "output path" on Visual Studio 2015 Community and x64 configuration

### ISSUE THREAD

**Issue by Simon-IT** [wixtoolset/issues#5470] opened 2017-01-05 15:30 UTC
Hi guys,
as showed in the attached image

![git1](https://cloud.githubusercontent.com/assets/24890180/21685795/3d431e6a-d363-11e6-9ae9-4aaf1f25ee35.png)

it's impossible to change the output path: in some case there are more than one copy of x64 configuration in the project file. If you remove all but one manually, then all works well.
Wix version: 3.10.3
Visual Studio 2015 Community Edition Version 14.0.25431.01 Update 3 

Thank you.
Regards,

Simone

**Comment by barnson** [comment] 2017-01-05 15:48
Duplicate of https://github.com/wixtoolset/issues/issues/3918.

**Closed by barnson** 2017-01-05 15:48 UTC
Labels: duplicate
