### ISSUE TITLE
not able to install Wix - V3 visual studio 2022 extension in visual studio professional 2022.

### ISSUE THREAD

**Issue by Shrinidhicy** [wixtoolset/issues#7689] opened 2023-08-23 06:30 UTC
## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are posted in [Discussions](https://github.com/orgs/wixtoolset/discussions/categories/announcements).

## Discussions and support

Note that discussions are best held in [Discussions](https://github.com/orgs/wixtoolset/discussions/new?category=questions). Please do not open issues requesting support or debugging help; first start a thread in [Discussions](https://github.com/orgs/wixtoolset/discussions/new?category=questions) and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Instructions

Read the sections above. Delete the Triage, Discussions and support, and Instructions sections and fill out the rest.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> wix - v3

* Which version of Visual Studio are you building with (if any)?

> visual studio professional 2022 17.7.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> wix - v3 visual studio 2022 extention

* Which version of .NET are you building with?

>..Net 7
* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Microsoft windows 10 pro (version 10.0.19045 build  19045)

* Describe the problem and the steps to reproduce it.

>1. Download the "WiX v3 - Visual Studio 2022 Extension" from https://marketplace.visualstudio.com/items?itemName=WixToolset.WixToolsetVisualStudio2022Extension
2. A file with the name "Votive2022.vsix" will be downloaded into Downloads folder
3. To install the extenstion, double click on Votive2022.vsix file.
Or
even if we install fron visual studio -> extensions -> wix -v3 visual studio 2022 extension -> download , close and open Visual studio again but installation fails with bellow message.
* Describe the behavior you expected and how it differed from the actual behavior.

>Expected behavior is, it should install successfully.
>Actual behavior is, it is failing with the error message:
"The install of WiX v3 - Visual Studio 2022 Extension" was not successful for all the selected products. For more information, click on the install log link at the bottom of the dialog."
[dd_VSIXInstaller_20230823113817_0718.log](https://github.com/wixtoolset/issues/files/12415755/dd_VSIXInstaller_20230823113817_0718.log)

**Comment by robmen** [comment] 2023-08-23 06:33
> 23-08-2023 11:38:30 - 	Extension is signed with an invalid timestamp.

Duplicate of #7433

**Closed by robmen** 2023-08-23 06:33 UTC
Labels: external
