### ISSUE TITLE
WiX breaks C++ Code Analysis

### ISSUE THREAD

**Issue by axelriet** [wixtoolset/issues#5297] opened 2016-05-14 08:52 UTC
It appears that the issue is known and was acknowledged several years ago: https://sourceforge.net/p/wix/bugs/3095/

It still reproes with WiX 3.10/3.11/4.0.3922.0 and Dev14 Update 2, is there a workaround?

**Comment by barnson** [comment] 2016-05-14 16:04
duplicate of https://github.com/wixtoolset/issues/issues/3781

**Closed by barnson** 2016-05-14 16:04 UTC
