### ISSUE TITLE
wix v4 - post build event command line - not working with macros

### ISSUE THREAD

**Issue by pwallner** [wixtoolset/issues#7023] opened 2022-11-16 11:46 UTC
## Bugs

* Which version of WiX are you building with?
4.0.0-preview.1

* Which version of Visual Studio are you building with (if any)?
VS 2022 (17.4.1)
VS 2019 (16.11.21)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
none

* Which version of .NET are you building with?
.NET Framework 4.7.2

* Describe the problem and the steps to reproduce it.
MSI Package post-build event command line ignores macros like `$(ProjectDir)` and `$(ProjectName)`, full command line:
```call "$(ProjectDir)CreateLocalizedInstallerAllLanguages.cmd" "$(ProjectDir)" "$(ProjectName)"```
I see following error:
```error MSB3073: Der Befehl "call "CreateLocalizedInstallerAllLanguages.cmd" "" """ wurde mit dem Code 1 beendet.```
and the macro is ignored.

* Describe the behavior you expected and how it differed from the actual behavior.
wix v3 is working with this command line, this is what I expected with v4

* Workaround
Use path instead of macro `$(ProjectDir)` and `$(ProjectName)` like
```call "C:\Users\...\WixApplication\CreateLocalizedInstallerAllLanguages.cmd" "C:\...\WixApplication" "WixApplication"```

everything is running well

**Comment by robmen** [comment] 2022-11-16 15:52
Duplicate of https://github.com/wixtoolset/issues/issues/7020

**Closed by robmen** 2022-11-16 15:52 UTC
Labels: duplicate
