### ISSUE TITLE
Wix Toolset Visual Studio 2022 Extensions crashes Visual Studio during Build

### ISSUE THREAD

**Issue by oholthau** [wixtoolset/issues#6697] opened 2022-01-04 09:55 UTC
* Which version of WiX are you building with?

v3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

Visual Studio 2022 17.0.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

Wix Toolset Visual Studio 2022 Extensions 1.0.0.18

* Which version of .NET are you building with?

.NET 4.8.30319

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Occurs during running of Heat.exe

* Describe the problem and the steps to reproduce it.

When Building the Setup project, Visual Studio crashed and restarts.
This could be found in the event logs:
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(System.String, System.Security.Policy.Evidence, Byte[], System.Configuration.Assemblies.AssemblyHashAlgorithm, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Reflection.Assembly.LoadFrom(System.String)
   at Microsoft.Tools.WindowsInstallerXml.Build.Tasks.WixToolTask.ExecuteToolThread(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)

* Describe the behavior you expected and how it differed from the actual behavior.

... not crashing Visual Studio...

**Comment by robmen** [comment] 2022-01-04 13:02
Please consider adding a link to a GitHub repo with your .sln and projects that reproduce the problem.

**Comment by CodeFontana** [comment] 2022-01-04 16:30
I know there's not enough information here yet to definitively diagnose this, but wanted to share I had encountered the exact same VS2022 crash with System.BadImageFormatException, and for me it was the same problem as #2467 

Before crashing, on the output window of VSS build was an error-- 
_Could not load file or assembly 'file:///C:\Program Files (x86)\Wix Toolset v3.11\bin\Heat.exe' or one of it's dependencies. An attempt was made to load a program with an incorrect format._

Note: This was the first attempt at building a Wix project in VS2022, coming from a project that was previously created and working fine in VS2019.

The solution was adding a &lt;PropertyGroup&gt; to the &lt;Project&gt; tag...

    <PropertyGroup>
        <RunWixToolsOutOfProc Condition=" '$(PROCESSOR_ARCHITECTURE)'!='x86' ">true</RunWixToolsOutOfProc>
    </PropertyGroup>

And modifying the &lt;HeatDirectory&gt; instruction...

    <HeatDirectory ...other attributes... RunAsSeparateProcess="$(RunWixToolsOutOfProc)" />

This same issue is also documented here:
https://stackoverflow.com/questions/49981194/wix-heat-exe-could-not-be-loaded-with-msbuild

Can you confirm is this is your issue?

**Comment by rseanhall** [comment] 2022-01-04 21:50
https://github.com/wixtoolset/issues/issues/2467 had incorrect advice, please refer to https://github.com/wixtoolset/issues/issues/6636 instead. No one should be using the `HeatDirectory` task directly.

**Comment by oholthau** [comment] 2022-01-05 09:34
Hi Brian,

Adding RunAsSeparateProcess has fixed my issue.

Thank you!

BR
Olaf.

**Comment by robmen** [comment] 2022-01-05 12:40
Duplicate of #6636

**Closed by robmen** 2022-01-05 12:40 UTC
Labels: harvester (heat)
