### ISSUE TITLE
3.x documentation missing diagram

### ISSUE THREAD

**Issue by paquettej** [wixtoolset/issues#5403] opened 2016-09-15 14:56 UTC
The page http://wixtoolset.org/documentation/manual/v3/overview/tools.html is missing the referenced diagram. Trying to view the image directly gives 

"The image “http://wixtoolset.org/documentation/manual/v3/content/WiX_Toolset_Diagram.png” cannot be displayed because it contains errors."

**Comment by sharazam** [comment] 2016-09-16 21:02
Confirmed on Firefox 48.0.2. I came here because of this. The real image (probably a backup) can be found at:

http://cml.s10.xrea.com/ej/WiX/imgs/WiX_Toolset_Diagram.png

So, I guess, just download and replace the image on the website...

**Comment by User5910** [comment] 2017-02-17 22:37
+1

**Comment by orithena** [comment] 2018-11-27 15:05
It's now the end of 2018 and the webmaster still didn't replace that image?

Although, it might very well be that the web server or CMS is the problem -- I see lots of 0xEF 0xBF 0xBD sequences in that file... which is the Unicode "unknown character" codepoint 0xFFFD ('�') in UTF8 encoding. Looks like this image file has been dragged through an ASCII->UTF8 converter or something like that...

I don't see any email address of the webmaster anywhere on wixtoolset.org ... does anybody know how to contact them?

**Comment by robmen** [comment] 2018-11-27 19:43
This is the place to file issues for the WiX Toolset website.

The root issue seems to be that the build machine (on AppVeyor) keeps checking this image out as text. The .gitattributes files are in place to supposedly prevent that but it isn't work. This is a low pri enough issue that I've not spent enough time to dig into the root problem.

You can see my latest quick attempt seems to have the same problem. :frowning_face:

**Comment by orithena** [comment] 2018-11-27 21:35
@robmen: This would be the .gitattributes file at wixtoolset/wix3? Have you tried to explicitely set `*.png binary` there?

**Comment by robmen** [comment] 2018-11-27 22:55
Yep, just tried it. Did not work. :disappointed: 

This is the repo in question: https://github.com/wixtoolset/web

**Comment by orithena** [comment] 2018-11-27 23:45
@robmen I don't know anything about C#, but web development is no stranger to me. From a cursory glance, I see that .png is not listed as MIME type image/png in src/Web/Startup.cs::StaticContentTypes(). This should be a default in any web framework, but I would check whether that system really does regard .png files outside the Static directory as static.

I've seen git to change line endings on text files, but I have never seen any further re-encoding... and the image in question checks out from that repo as valid on my end, so I don't think it has been wrongly checked in. I don't think that git is the culprit (unless it's a non-standard git client that is deploying that repo to the application server).

Also, I would check whether the deployment credential secrets in appveyor.yml are still valid -- and change them if they are. And then I would make sure that this file with the new credentials is never published again! (see https://stackoverflow.com/questions/9794931/keep-file-in-a-git-repo-but-dont-track-changes)

**Comment by seekingtheoptimal** [comment] 2019-12-18 14:31
Still broken: https://wixtoolset.org/documentation/manual/v3/overview/tools.html
Is it really that hard to insert an image on a website since 2016? : )
Worst case just upload it to "anywhere" (like literally) and link it with absolute url.
![image](https://user-images.githubusercontent.com/17144089/71094387-2f01e900-21ab-11ea-98e2-65d0d60932bb.png)

**Comment by robmen** [comment] 2019-12-18 14:43
The image is there. It is (in some way) broken on the web. The image is correct in the wix.chm.

My quick attempts to fix it failed (that is why the issue was reopened). This is a low priority issue for me so I went back to writing code and fixing bugs.

Perhaps you can sort out what happened to the image between wix.chm build and web site publish?

**Comment by seekingtheoptimal** [comment] 2019-12-19 10:55
The [image](https://github.com/wixtoolset/wix3/blob/develop/src/chm/files/content/WiX_Toolset_Diagram.png ) in the repository is 108KB whereas in chrome dev tools I see that content length is around 188KB.
I don't see exactly from the source code why it does not work, but _it is the same for all static image files regardless of file types_, which narrows it down for me either to the UseStaticFiles config/path issues (which seems okay), or all static images are transformed in some way during the build. Without access to the hosting platform I'm not sure at what step this actually happens (when _documents_ and _files_ directories are merged, or when it goes to the blob, or after it already got pulled down on the Web build, etc..).
But yeah since the images can be found on github anyway, I agree with the low priority you mentioned )

**Comment by cwellsx** [comment] 2020-12-22 16:44
The corrupt image begins like this:

![image](https://user-images.githubusercontent.com/2397556/102911709-b946f200-447c-11eb-84e4-b1693f818ac4.png)

Given that it begins with `EF BF BD` I think that https://stackoverflow.com/questions/38018263/what-is-the-format-or-encoding-of-a-file-with-data-like-this implies that something (incorrectly) thought it was text and tried to convert it to UTF-8.

**Closed** 2022-11-21 08:09 UTC
Labels: bug, documentation
