### ISSUE TITLE
Installer fails to create a database when TLS 1.0 is disabled

### ISSUE THREAD

**Issue by baronics** [wixtoolset/issues#5794] opened 2018-04-11 17:23 UTC
If this issue is a bug:

* Which version of WiX are you building with?

>3.11.1

* Which version of Visual Studio are you building with (if any)?

> 2017

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.21.62588

* Which version of .NET are you building with?

> 4.7.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 with SQL Server 2016

* Describe the problem and the steps to reproduce it.

> The setup program was installing successfully until TLS 1.0 was disabled while keeping TLS 1.1 and 1.2 enabled.
The failure occurs when the SQL extension call to SQLDatabase is made.
From the log:
CreateDatabase:  Error 0x80004005: failed to create to database: 'dbname', error: unknown error
Error 26201. Error -2147467259: failed to create SQL database: dbname, error detail: unknown error.
MSI (s) (EC!58) [11:35:06:020]: Product: productname -- Error 26201. Error -2147467259: failed to create SQL database: dbname, error detail: unknown error.

* Describe the behavior you expected and how it differed from the actual behavior.

> Expecting the call to succeed by using TLS 1.1 or 2.0

**Comment by barnson** [comment] 2018-04-11 17:50
Duplicate of https://github.com/wixtoolset/issues/issues/5543

**Closed by barnson** 2018-04-11 17:50 UTC
Labels: duplicate

**Comment by baronics** [comment] 2018-04-11 17:57
#5543 was about failure when TLS 1.2 was enabled, this issue is when TLS 1.0 disabled.
If it is the same, then which release of WIX can I find the fix?

**Comment by barnson** [comment] 2018-04-11 22:35
It appears to be the same issue. No fix is yet available.

**Comment by churstz** [comment] 2020-07-30 15:55
As Microsoft has undeprecated the OLEDB Driver and it now includes support for TLS 1.2, a better solution would probably be to change the CLSID_SQLOLEDB of the OLEDB Provider to the CLSID_MSOLEDBSQL (or MSOLEDBSQL_CLSID) for the MS OLEDB Provider such that TLS 1.2 support is included.

The fact that TLS is factoring in to an unencrypted connection is luda out of the gate.  In our case TLS 1.2 was explicitly enabled and TLS 1.0, 1.1 were explicitly disabled in the SCHANNEL registry causing the SQL Connection failure.  Explicitly had to enable TLS 1.0 and 1.1 for the installer to execute.

For Reference
https://docs.microsoft.com/en-us/sql/connect/oledb/oledb-driver-for-sql-server?view=sql-server-ver15

https://docs.microsoft.com/en-us/sql/connect/oledb/ole-db-driver/establishing-a-connection-to-a-data-source?view=sql-server-ver15
