### ISSUE TITLE
Extension installed through 'wix extension add' not found

### ISSUE THREAD

**Issue by Mythra** [wixtoolset/issues#8088] opened 2024-03-30 21:11 UTC
### WiX Version

4.0.5

### .NET or MSBuild or Visual Studio Version

8.0.202

### HeatWave Version

N/A

### Windows Version

windows-2022 20240322.1.0

### Repro Repo

https://github.com/rem-verse/sprig

### Repro Steps

For an actual job execution see: <https://github.com/rem-verse/sprig/actions/runs/8493341595/job/23267325848>
Workflow steps are: <https://github.com/rem-verse/sprig/blob/f180bd7bc8fb409c2a5a379967e6b1067a21d036/.github/workflows/package.yml#L19-L26>

Effectively:

1. Install wix with: `dotnet tool install --global wix`.
2. Add wix extensions with: `wix extension add WiXToolset.UI.wixext` & `wix extension add WiXToolset.Util.wixext`
3. Try to build the package with those extensions: `wix build sprig.wxs -ext WiXToolset.Util.wixext -ext WiXToolset.UI.wixext -defaultcompressionlevel high -arch "x64" -bindpath "../../"`

### Actual Result

After adding extensions on a fresh install those extensions are reported as not being found:

```
wix.exe : error WIX0144: The extension 'WiXToolset.Util.wixext' could not be found. Checked paths: WiXToolset.Util.wixext, D:\a\sprig\sprig\installer-scripts\win\.wix\extensions\WiXToolset.Util.wixext\5.0.0-rc.2\wixext4\WiXToolset.Util.wixext.dll
```

### Expected Result

I expected for the extension to be found, and the build to succeed.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment] 2024-03-30 21:16
https://github.com/wixtoolset/issues/issues/8044#issuecomment-1994319845

Dupe of https://github.com/wixtoolset/issues/issues/8033.

**Closed by barnson** 2024-03-30 21:16 UTC
Labels: triage
