### ISSUE TITLE
Missing diagram from http://wixtoolset.org/documentation/manual/v3/overview/tools.html

### ISSUE THREAD

**Issue by novabe** [wixtoolset/issues#5687] opened 2017-09-25 21:34 UTC
Missing diagram from http://wixtoolset.org/documentation/manual/v3/overview/tools.html

**Comment by barnson** [comment] 2017-09-25 22:02
Duplicate of https://github.com/wixtoolset/issues/issues/5403.

**Closed by barnson** 2017-09-25 22:02 UTC
Labels: duplicate
