### ISSUE TITLE
Burn prefers local files, even with hash mismatch

### ISSUE THREAD

**Issue by papeh** [wixtoolset/issues#6818] opened 2022-06-30 16:53 UTC
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

> 2017 Community (Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework)

* Which version of .NET are you building with?

> .NET Framework 4.6.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Edition	Windows 10 Pro
> Version	21H2
> Installed on	‎8/‎21/‎2020
> OS build	19044.1706
> Experience	Windows Feature Experience Pack 120.2212.3740.0

* Describe the problem and the steps to reproduce it.

When installing an ExePackage with a RemotePayload, if a different version exists in %UserProfile%\Downloads\<Name>, the installer checks the the local file's hash against the RemotePayload's Hash, then fails because of a hash mismatch.

Steps:

0. Ensure no Microsoft Visual C++ 2015+ Redistributables (x64) are installed
1. Download [an unexpected version of the Visual C++ 14 Redistributable](https://download.visualstudio.microsoft.com/download/pr/ed95ef9e-da02-4735-9064-bd1f7f69b6ed/CE6593A1520591E7DEA2B93FD03116E3FC3B3821A0525322B0A430FAA6B3C0B4/VC_redist.x64.exe) to %USERPROFILE%\Downloads\VC_redist.x64.exe
2. Attempt to install a program that downloads the redistributable if needed

[WiX Fragment](https://github.com/sillsdev/genericinstaller/blob/06779e04012bfab1b912af23ff7b4c442a344fbb/BaseInstallerBuild/Bundle.wxs#L320):
```
<?define VC15to19RedistWebLink = https://download.visualstudio.microsoft.com/download/pr/36e45907-8554-4390-ba70-9f6306924167/97CC5066EB3C7246CF89B735AE0F5A5304A7EE33DC087D65D9DFF3A1A73FE803/VC_redist.x64.exe ?>
<Fragment>
	<util:RegistrySearch Root="HKLM"
				Key="SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\X64"
				Variable="CPP14RedistBld"
				Value="Bld"
				Result="value"
				Win64="yes"/>
	<WixVariable Id="CPP14DetectCondition" Overridable="yes" Value="CPP14RedistBld &gt;= 30040" />
	<PackageGroup Id="redist_vc15to19">
		<ExePackage Id="vc14" Cache="no" PerMachine="yes" Vital="yes" Compressed="no" Permanent="yes"
				DownloadUrl="$(var.VC15to19RedistWebLink)"
				InstallCommand="/quiet /norestart"
				DetectCondition="!(wix.CPP14DetectCondition)">
			<RemotePayload 
				Size="25169400"
				Version="14.29.30040.0"
				ProductName="Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.28.29914"
				Description="Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.28.29914"
				Hash="9ADE54D322BE27BFF05D5AFEC8ED44F9B2D9306E" />
			<ExitCode Value="1638" Behavior="success"/> <!-- Don't fail if newer version is installed -->
		</ExePackage>
	</PackageGroup>
</Fragment>
```

Relevant Log Section:
```
[3584:477C][2022-06-20T08:58:56]i300: Apply begin
[3584:477C][2022-06-20T08:58:56]i010: Launching elevated engine process.
[3584:477C][2022-06-20T08:58:58]i011: Launched elevated engine process.
[3584:477C][2022-06-20T08:58:59]i012: Connected to elevated engine.
[446C:3780][2022-06-20T08:58:59]i358: Pausing automatic updates.
[446C:3780][2022-06-20T08:58:59]i359: Paused automatic updates.
[446C:3780][2022-06-20T08:58:59]i360: Creating a system restore point.
[446C:3780][2022-06-20T08:58:59]i361: Created a system restore point.
[446C:3780][2022-06-20T08:58:59]i370: Session begin, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{5a438c9c-224e-485f-94f1-245baed51345}, options: 0x7, disable resume: No
[446C:3780][2022-06-20T08:58:59]i000: Caching bundle from: 'C:\Users\user\AppData\Local\Temp\{C8044F4D-56A2-4E2F-95F9-93316F95E59A}\.be\FieldWorks_9.1.12.1_Online.exe' to: 'C:\ProgramData\Package Cache\{5a438c9c-224e-485f-94f1-245baed51345}\FieldWorks_9.1.12.1_Online.exe'
[446C:3780][2022-06-20T08:58:59]i320: Registering bundle dependency provider: {5a438c9c-224e-485f-94f1-245baed51345}, version: 9.1.12.1
[446C:3780][2022-06-20T08:58:59]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{5a438c9c-224e-485f-94f1-245baed51345}, resume: Active, restart initiated: No, disable resume: No
[3584:44B4][2022-06-20T08:58:59]i338: Acquiring package: vc14, payload: vc14, copy from: C:\Users\user\Downloads\vc_redist.x64.exe
[3584:44B4][2022-06-20T08:58:59]i000: Setting string variable 'WixBundleLastUsedSource' to value 'C:\Users\user\Downloads\'
[446C:3CEC][2022-06-20T08:58:59]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\vc14, expected: 9ADE54D322BE27BFF05D5AFEC8ED44F9B2D9306E, actual: AE97F1E35C50A3C1B7B231995AD547828E71FE4C
[446C:3CEC][2022-06-20T08:58:59]e000: Error 0x80091007: Failed to verify hash of payload: vc14
[446C:3CEC][2022-06-20T08:58:59]e310: Failed to verify payload: vc14 at path: C:\ProgramData\Package Cache\.unverified\vc14, error: 0x80091007. Deleting file.
[446C:3CEC][2022-06-20T08:58:59]e000: Error 0x80091007: Failed to cache payload: vc14
[3584:44B4][2022-06-20T08:58:59]e314: Failed to cache payload: vc14 from working path: C:\Users\user\AppData\Local\Temp\{C8044F4D-56A2-4E2F-95F9-93316F95E59A}\vc14, error: 0x80091007.
[3584:44B4][2022-06-20T08:58:59]e349: Application requested retry of payload: vc14, encountered error: 0x80091007. Retrying...
[3584:44B4][2022-06-20T08:59:03]i338: Acquiring package: vc14, payload: vc14, copy from: C:\Users\user\Downloads\vc_redist.x64.exe
[446C:3CEC][2022-06-20T08:59:03]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\vc14, expected: 9ADE54D322BE27BFF05D5AFEC8ED44F9B2D9306E, actual: AE97F1E35C50A3C1B7B231995AD547828E71FE4C
[446C:3CEC][2022-06-20T08:59:03]e000: Error 0x80091007: Failed to verify hash of payload: vc14
[446C:3CEC][2022-06-20T08:59:03]e310: Failed to verify payload: vc14 at path: C:\ProgramData\Package Cache\.unverified\vc14, error: 0x80091007. Deleting file.
[446C:3CEC][2022-06-20T08:59:03]e000: Error 0x80091007: Failed to cache payload: vc14
[3584:44B4][2022-06-20T08:59:03]e314: Failed to cache payload: vc14 from working path: C:\Users\user\AppData\Local\Temp\{C8044F4D-56A2-4E2F-95F9-93316F95E59A}\vc14, error: 0x80091007.
[3584:44B4][2022-06-20T08:59:03]e349: Application requested retry of payload: vc14, encountered error: 0x80091007. Retrying...
[3584:44B4][2022-06-20T08:59:06]i338: Acquiring package: vc14, payload: vc14, copy from: C:\Users\user\Downloads\vc_redist.x64.exe
[446C:3CEC][2022-06-20T08:59:06]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\vc14, expected: 9ADE54D322BE27BFF05D5AFEC8ED44F9B2D9306E, actual: AE97F1E35C50A3C1B7B231995AD547828E71FE4C
[446C:3CEC][2022-06-20T08:59:06]e000: Error 0x80091007: Failed to verify hash of payload: vc14
[446C:3CEC][2022-06-20T08:59:06]e310: Failed to verify payload: vc14 at path: C:\ProgramData\Package Cache\.unverified\vc14, error: 0x80091007. Deleting file.
[446C:3CEC][2022-06-20T08:59:06]e000: Error 0x80091007: Failed to cache payload: vc14
[3584:44B4][2022-06-20T08:59:06]e314: Failed to cache payload: vc14 from working path: C:\Users\user\AppData\Local\Temp\{C8044F4D-56A2-4E2F-95F9-93316F95E59A}\vc14, error: 0x80091007.
[3584:477C][2022-06-20T08:59:06]e000: Error 0x80091007: Failed while caching, aborting execution.
[446C:3780][2022-06-20T08:59:06]i372: Session end, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{5a438c9c-224e-485f-94f1-245baed51345}, resume: None, restart: None, disable resume: No
[446C:3780][2022-06-20T08:59:06]i330: Removed bundle dependency provider: {5a438c9c-224e-485f-94f1-245baed51345}
[446C:3780][2022-06-20T08:59:06]i352: Removing cached bundle: {5a438c9c-224e-485f-94f1-245baed51345}, from path: C:\ProgramData\Package Cache\{5a438c9c-224e-485f-94f1-245baed51345}\
[446C:3780][2022-06-20T08:59:06]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{5a438c9c-224e-485f-94f1-245baed51345}, resume: None, restart initiated: No, disable resume: No
[3584:477C][2022-06-20T08:59:06]i399: Apply complete, result: 0x80091007, restart: None, ba requested restart:  No
```

* Describe the behavior you expected and how it differed from the actual behavior.

Expected: the installer ignores the user-downloaded payload, especially when the hash doesn't match.
Actual: the installer tries several times to verify the hash of the same, already-downloaded file, but never tries to download the correct file from the specified DownloadUrl.

**Comment by rseanhall** [comment] 2022-06-30 16:57
Duplicate of https://github.com/wixtoolset/issues/issues/3640

**Comment by rseanhall** [comment] 2022-07-01 19:01
After looking at this again, it looks like #3640 won't actually change the default behavior for a slightly modified scenario where the payload is validated with Authenticode or the file size is correct but the hash is wrong. If the BA asks to retry the payload acquisition without overriding the selection of the local file (the default behavior for BAs built on BalBaseBootstrapperApplication), then the engine will end up picking the same local file that failed instead of trying to pick a different local file or trying to download it.

**Comment by robmen** [comment] 2022-07-07 20:25
I updated the title to reflect this is a general Burn behavior.

The `RemotePayload` element does not necessarily mean that the payload is only available for download (although given the element name, it is easy to think that they do). `RemotePayload` only means the payloads are not available at build time. The RemotePayloads could be copied relative to the final bundle exe output and "shipped on the CD" (which is also the -layout scenario). So, despite their name RemotePayloads may actually be found local.

**Closed** 2022-08-03 20:57 UTC
Labels: burn, burn-acquisition
