### ISSUE TITLE
ServiceConfig breaks the build

### ISSUE THREAD

**Issue by BPodszun** [wixtoolset/issues#7244] opened 2023-02-24 08:06 UTC
* Which version of WiX are you building with?

4.0.0-rc.2

* Which version of Visual Studio are you building with (if any)?

Version 17.4.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

FireGiant HeatWave 0.9.4.1

* Which version of .NET are you building with?

4.8.09032

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

n/a (but Win11)

* Describe the problem and the steps to reproduce it.

I know that `ServiceConfig` has a remark that it's considered frail, but since `util:ServiceConfig` is just not a valid replacement for my use case (set the service start to delayed) I wanted to go ahead and silence the warning, try it anyway.

My simple test case is

```
<ServiceInstall 
                Id="svc_WinlogbeatInst" 
                Name="winlogbeat" 
		Description="bar" 
		Type="ownProcess" 
		Vital="yes" 
		Start="auto" 
		Account="LocalSystem"
		ErrorControl="normal">
		<ServiceConfig DelayedAutoStart="yes" OnInstall="yes" OnReinstall="yes" />
</ServiceInstall>
```

and the build fails with

> WIX0136	There was an error importing the file 'C:\MyPath\obj\x64\Debug\_idts\MsiServiceConfigFailureActions.idt'.	AgentInstaller	C:\MyPath\obj\x64\Debug\_idts\MsiServiceConfigFailureActions.idt	1	

The contents of that file is

```
MsiServiceConfigFailureActions	Name	Event	ResetPeriod	RebootMessage	Command	Actions	DelayActions	Component_
s72	l255	i2	I4	L255	L255	S0	S0	s72
MsiServiceConfigFailureActions	MsiServiceConfigFailureActions
winlogbeat.DS	winlogbeat	5	3	0	cmp_Winlogbeat			
```

(unfortunately I don't understand IDT files)

* Describe the behavior you expected and how it differed from the actual behavior.

I expected the `ServiceConfig` element to at least compile / be turned into a valid MSI - in spite of the remarks/warnings that it's potentially having issues.

**Comment by robmen** [comment] 2023-02-24 08:08
Duplicate of #7198

**Closed by robmen** 2023-02-24 08:08 UTC
Labels: duplicate
