### ISSUE TITLE
.NET Framework license page not found

### ISSUE THREAD

**Issue by mediawolf** [wixtoolset/issues#5346] opened 2016-07-07 12:04 UTC
My boostrapper depends on .NET 4.5.
When installing bundle on a computer having no such framework, standard WIX window appears that proposes user to install required .NET Framework. Also there is link to a license agreement which points to http://wixtoolset.org/licenses/netfx452 that produces "Page Not Found" error.

**Comment by robmen** [comment] 2016-07-07 16:27
Dupe of #4180

**Closed by robmen** 2016-07-07 16:27 UTC
Labels: duplicate
