### ISSUE TITLE
Ensure WiX mitigates MSBuild changes in Visual Studio 2019

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5894] opened 2018-10-29 21:48 UTC
WiX v3 and v4 both have intimate dependencies on MSBuild behavior that might be affected by a change coming in Visual Studio 2019. https://github.com/Microsoft/msbuild/issues/3778

**Comment by robmen** [comment] 2018-11-05 14:43
WiX v3.14 no longer checks for MSBuild version because it only supports MSBuild v4+. That _should_ avoid the problems described in the linked issue. Now need an MSBuild v16 build to verify.

**Comment by chrpai** [comment] 2018-12-05 13:59
VS2019 Preview 1 was released yesterday.  I'd be happy to test it if a 2019 Votive AddIn could be generated.

**Comment by rseanhall** [comment] 2019-01-02 02:09
Based on https://github.com/wixtoolset/VisualStudioExtension/pull/10, it appears that this MSBuild change does cause issues with VS2019 and versions of WiX earlier than v3.14. So unless the `Update MSBuild fallback logic to reduce breaking change impact` part of that MSBuild issue is implemented and addresses our usage, Votive will have to update its VS2019 v3 redirect targets. Either we'll have to ensure that the installed version is v3.14 or we'll have to add the logic from the pull request to bypass the legacy wix.targets that checked the MSBuild version.

**Comment by chrpai** [comment] 2019-01-04 14:01
I made a private build of Votive using @drolevar's ropos containing his msbuild pull request.  Tested  VS2019 Preview 1 with WiX 3.10, 3.11 and a private build of 3.14 and all the scenarios look good to me.

**Comment by dgnuff** [comment] 2019-01-27 07:31
I've just installed VS 2019 Preview 2, I'm still using WiX 3.11 and the matching version of Votive.  Without any changes, WiX projects don't load properly, however, I have an interim fix that should allow people using 3.11 and VS 2019 to load projects.

Attached is my modified WiX targets that appears to provide a fix.  Since 3.14 is on the roadmap, and fixes this anyway, I suspect that there isn't a real need to patch this into 3.11, but it may prove handy to other people that get stuck in the same situation I'm in.

**Comment by rseanhall** [comment] 2019-02-07 00:04
MSBuild has created https://github.com/Microsoft/msbuild/issues/4150 in the 16.0 Milestone to address the breaking change with `$(MSBuildToolsVersion)` in numeric comparisons.

**Comment by chrpai** [comment] 2019-02-09 02:09
I'll try to keep an eye on this and retest once it's available.  For example I'm updating to 16.0 preview 2.2 now.  I don't know which release this MSBuild fix will be in  so if someone happens to become aware of it  feel free to ping me and I'll retest.

**Comment by chrpai** [comment] 2019-02-13 22:01
Updated to Preview 3 today.  Regression still present.  Will keep on the lookout for new versions with the fix.

**Comment by chrpai** [comment] 2019-02-27 21:01
VS 2019 Preview 4 just dropped today and everything looks great.

**Closed** 2019-02-27 22:11 UTC
Labels: external, msbuild
