### ISSUE TITLE
Error "The Directory/@Name attribute's value is not a relative path" when running wix4 in Linux Ubuntu

### ISSUE THREAD

**Issue by pablochacin** [wixtoolset/issues#7154] opened 2023-01-12 15:25 UTC
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

4.0.0-rc.1+6580fe7b

* Which version of Visual Studio are you building with (if any)?

N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

N/A

* Which version of .NET are you building with?

7.0.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

N/A 

* Describe the problem and the steps to reproduce it.

When testing on a Linux environment (Ubuntu 22.04) a get the error ""The Directory/@Name attribute's value is not a relative path" for every "Directory" element. 

To reproduce the error in Ubuntu

Install dotnet in Linux
```bash
sudo apt install -y dotnet-core-7.0 dotnet-sdk-7.0
```
Install wix4 
```bash
dotnet tool install --global wix --version 4.0.0-rc.1 
```
Download this test .wsx file from the wix4 project
```bash
wget https://raw.githubusercontent.com/wixtoolset/wix4/develop/src/test/msi/TestData/Templates/Product.wxs
```

Try building the .wsx file
```bash
wix build -d PackageName=mypackage -d TestGroupName=mytest -d UpgradeCode=$(uuidgen) Product.wxs

/tmp/wix4/Product.wxs(32) : error WIX0389: The Directory/@Name attribute's value, '~Test WiX', is not a relative path.
/tmp/wix4/Product.wxs(33) : error WIX0389: The Directory/@Name attribute's value, 'mytest', is not a relative path.
/tmp/wix4/Product.wxs(34) : error WIX0389: The Directory/@Name attribute's value, 'mypackage', is not a relative path.
```

* Describe the behavior you expected and how it differed from the actual behavior.

Wix4 is a dotnet application. I would expect it to work in Linux environment.

**Comment by robmen** [comment] 2023-01-12 15:36
> Wix4 is a dotnet application. I would expect it to work in Linux environment.

This expectation is incorrect. WiX depends on Windows APIs that are not abstracted by .NET on other operating systems. Therefore, it is necessary to re-implement several APIs for other platforms. We did restructure WiX v4 to (hopefully) make that easier to execute but no one stepped up to complete the work.

Until that work is completed, there is no expectation that WiX will run on Linux (or Mac).

**Comment by pablochacin** [comment] 2023-01-12 16:03
> Therefore, it is necessary to re-implement several APIs for other platforms. 
> Until that work is completed, there is no expectation that WiX will run on Linux (or Mac).

Thanks for the quick reply. Is there any place to start looking at which APIs are those?

**Comment by robmen** [comment] 2023-01-12 16:15
It isn't as clean as it should be, but you'll want to look at:

1. `WixToolset.Core.Native` - https://github.com/wixtoolset/wix4/tree/develop/src/wix/WixToolset.Core.Native
2. All P/Invoke in https://github.com/wixtoolset/wix4/tree/develop/src/wix that wasn't migrated to `WixToolset.Core.Native`
3. Any references from https://github.com/wixtoolset/wix4/tree/develop/src/wix to `WixToolset.Dtf.*`

If this project was to be undertaken in earnest, the PInvoke in 2 and 3 (and any I've missed) should be evaluated for better abstraction.

**Comment by robmen** [comment] 2023-01-14 05:10
Duplicate of #4381

**Closed by robmen** 2023-01-14 05:10 UTC
Labels: duplicate
