### ISSUE TITLE
Wix4: HarvestFile produces an invalid output when harvesting a TypeLib file

### ISSUE THREAD

**Issue by kirazy** [wixtoolset/issues#7383] opened 2023-04-08 04:31 UTC
* Which version of WiX are you building with?

> 4.0.0

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Professional 2022 17.5.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> HeatWave v1

* Which version of .NET are you building with?

> .NET Framework 4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Configuration: Release
> Platform: x64
>
> Using WixToolset.Heat, 4.0.0.
> 
> I am attempting to use HarvestFile on a TypeLib file to extract the COM registration information:
> ```
> <PropertyGroup>
>     <HarvestFileDirectoryRefId>INSTALLFOLDER</HarvestFileDirectoryRefId>
>     <HarvestFileComponentGroupName>Components.Project</HarvestFileComponentGroupName>
> </PropertyGroup>
> 
> <ItemGroup>
>     <HarvestFile Include="..\Project\bin\x64\Release\net48\Project.tlb" />
> </ItemGroup>
> ```
>
> It is able to produce the expected registration information, however Build then fails with errors:
> `WIX0047: The TypeLib element is non-advertised and therefore requires a parent File element.`
> `WIX0010: TheTypeLib/@Language attribute was not found; it is required.`
>
> Nesting the TypeLib entry within the File element and adding the language attribute resolves the issues.

* Describe the behavior you expected and how it differed from the actual behavior.

> I would expect that the TypeLib attribute would be nested inside the File element, and that the required attributes would be present.

**Comment by barnson** [comment] 2023-04-08 14:27
Duplicate of https://github.com/wixtoolset/issues/issues/3412.

**Closed** 2023-04-18 17:15 UTC
Labels: duplicate
