### ISSUE TITLE
The code has broken after upgrading to .NET 8

### ISSUE THREAD

**Issue by Praveer1981** [wixtoolset/issues#8541] opened 2024-06-03 08:31 UTC
### WiX Version

V3

### .NET or MSBuild or Visual Studio Version

.NET 8

### HeatWave Version

Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.10.0

### Windows Version

Windows server 2023

### Repro Steps

1.  downloaded the plugin from [WixToolsetVisualStudio2022Extension](https://marketplace.visualstudio.com/items?itemName=WixToolset.WixToolsetVisualStudio2022Extension) and installed it 
2.  When I compile my project I get below errors:

Error (active)	CS0246	The type or namespace name 'CustomAction' could not be found (are you missing a using directive or an assembly reference?)
Error (active)	CS0246	The type or namespace name 'ActionResult' could not be found (are you missing a using directive or an assembly reference?)
Error (active)	CS0246	The type or namespace name 'Session' could not be found (are you missing a using directive or an assembly reference?)

is there any cahnge in the library ? How can I find the replacement of CustomAction, ActionResult, Session? is there any other plugin I need to install ? 
![image](https://github.com/wixtoolset/issues/assets/24364597/03d11b8f-b721-40ba-92ae-4252a8b13186)

### Actual Result

It should not give any errors. 

### Acknowledgements

- [x] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by Praveer1981** [comment] 2024-06-03 08:34
can somebody guide me how to move forward ?

**Comment by dcm99** [comment] 2024-06-04 07:11
Hello,
There is a [wip](https://github.com/wixtoolset/issues/issues/7932#issue-2050684377) that addresses this feature. Currently you are limited to .Net Framework up to version 4.7.2.

**Comment by wmanning** [comment] 2024-06-13 02:03
@Praveer1981 Why can't you revert your custom action project back to .net framework?  
Do you have other projects in the solution maybe as .net 8 and you can't mix them?  Trying to think of a valid reason.  

Can you confirm you are using Wix 3.x?

**Comment by Praveer1981** [comment] 2024-06-13 02:23
> @Praveer1981 Why can't you revert your custom action project back to .net framework? Do you have other projects in the solution maybe as .net 8 and you can't mix them? Trying to think of a valid reason.
> 
> Can you confirm you are using Wix 3.x?

@wmanning  Thanks a lot for your response. We are in the middle of moving our project from .net framework to .NET 8. We use VS2022 and using Wixtoolset 3.11 plugin. Infact I also tried using heatmap.

I am not quite sure wheter we can mix up them up. looking for your advice.

**Comment by wmanning** [comment] 2024-06-13 02:40
If your custom action project doesn't reference anything from your .net 8 projects I don't see any reason not to mix them in the same solution. I could be missing something though.

.net uses the newer SDK-style csproj format where .net framework uses old csproj style.  
https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview

I had .net framework 4.0 projects that I converted to SDK-style csproj format with no issues.  This is what I had to do: https://stackoverflow.com/a/75316507/623561.  I converted them before I moved to Wix 4 as Wix 4 uses the new SDK-style csproj format.  I not sure if I needed to but it is much cleaner.

**Comment by Praveer1981** [comment] 2024-06-13 04:14
@wmanning  In my case, since we are upgrading all of our project to .NET 8 , my `custom action` project has dependency on the libraries that are built on .NET8

**Comment by dcm99** [comment] 2024-06-13 06:53
A bennefit from the new SDK Style project format is that you can now very easy multitarget your projects.
You can switch `<TargetFramework>net8.0-windows</TargetFramework>` to `<TargetFrameworks>net472;net8.0-windows</TargetFrameworks>` in the csproj file from the shared dependency.
If you are using ".net 8 only" stuff in your library, things getting a bit more complicated. But if you are only using newer c# language features, setting `<LangVersion>latest</LangVersion>` is often enough.

**Comment by robmen** [comment] 2024-06-15 20:12
Duplicate of #7932

**Closed by robmen** 2024-06-15 20:12 UTC
Labels: duplicate
