### ISSUE TITLE
ThmViewer not showing only pages, no layouts

### ISSUE THREAD

**Issue by jfro** [wixtoolset/issues#6170] opened 2020-05-06 16:58 UTC
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.2

* Which version of Visual Studio are you building with (if any)?

> Using CLI tools, but use VS2019 for our product

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> None

* Which version of .NET are you building with?

> .NET 4.x not sure, our app is .NET Core 3.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Opening any of the themes/ files in ThmViewer produces just a list of pages but i can't see any actual UI/layouts. Tried HyperlinkTheme.xml & RtfLargeTheme.xml for example.

* Describe the behavior you expected and how it differed from the actual behavior.

> My understanding is I should be able to see the full layouts

**Comment by rseanhall** [comment] 2020-05-06 21:54
Probably duplicate of https://github.com/wixtoolset/issues/issues/4860

**Closed** 2020-05-13 23:30 UTC
Labels: duplicate
