### ISSUE TITLE
Wix 4(Heat) is not working in vs2017 and msbuild 15

### ISSUE THREAD

**Issue by vnkishortech** [wixtoolset/issues#5941] opened 2019-01-31 07:33 UTC
If this issue is a bug:

Which version of WiX are you building with?
(WiX version in major.minor.release.build format)
v4.0.0.5918

Which version of Visual Studio are you building with (if any)?
(Visual Studio version, including year and update)
VS 2017 (update 15.9)

Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
(WiX Toolset Visual Studio Extension version in major.minor.release.build format)
Not using any vs extensions

Which version of .NET are you building with?
(.NET version) .net 4.6.2

If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
(Windows version) 

Describe the problem and the steps to reproduce it.
(Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

The below heat command is not working with VS 2017 and msbuild 15 because ToolsVersion="15.0" is set in .csproj in vs2017.
heat project "MyProject.csproj" -pog:Binaries -ag -template:fragment -out project.wxs

Describe the behavior you expected and how it differed from the actual behavior.
(Be as specific as you can and err on the side of providing too much information.)

**Comment by barnson** [comment] 2019-01-31 17:51
Duplicate of https://github.com/wixtoolset/issues/issues/5490.

**Closed by barnson** 2019-01-31 17:51 UTC
Labels: duplicate
